jsexception.access.denied=no tiene permiso para realizar la acci\u00f3n solicitada. Inicie sesi\u00f3n como usuario permitido si puede.
jsexception.any={0}

jsexception.bean.has.no.method=El bean con nombre{0} no tienes m\u00e9todo {1}.
jsexception.bean.name.not.found.for.interface=No se ha encontrado ning\u00fan nombre de bean para la interfaz {0}.
jsexception.bean.no.name=No existe un bean con el nombre {0}.
jsexception.bean.not.a.ReportDataSourceService=El bean {0} no es un ReportDataSourceService.

jsexception.call.not.supported=Los objetos de b\u00fasqueda de recursos no admiten la llamada.
jsexception.connection.type.not.suported=No se admite este tipo de conexi\u00f3n.
jsexception.connection.uri.not.specified=URI de conexi\u00f3n no especificado
jsexception.could.not.find.resource.with.uri=No existe el recurso con URI {0}. 
jsexception.could.not.find.content.resource.with.uri=No existe el recurso de contenido con URI {0}.
jsexception.unexpected.resource.type.at.uri=Tipo inesperado ({0}) del recurso con la URI {1} 

jsexception.default.message=Se ha producido un error desconocido. P\u00f3ngase en contacto con el administrador de su sistema.

jsexception.error.creating.connection=Se produjo un error al crear la conexi\u00f3n. Vuelva a intentarlo.
jsexception.parameter.has.multiple.values=El par\u00e1metro {0} tiene varios valores.

jsexception.parameter.has.no.value=El par\u00e1metro {0} no tiene ning\u00fan valor.


jsexception.failed.to.create.connection=No se ha podido realizar la conexi\u00f3n.
jsexception.failed.to.save.connection=No se guard\u00f3 la conexi\u00f3n.
jsexception.failed.to.save.connection.changes=No se guardaron los cambios de la conexi\u00f3n.
jsexception.file.resource.is.reference=El recurso de archivo {0} es una referencia y no tiene datos.
jsexception.file.resource.no.match.type=El tipo declarado del recurso ({0}) no coincide con el tipo real de la referencia ({1}).
jsexception.folder.already.exists=Ya existe una carpeta con el nombre {0}. Elija un nombre diferente.
jsexception.folder.details.not.found=No se han encontrado detalles de carpeta de la carpeta {0} en la informaci\u00f3n de importaci\u00f3n. 
jsexception.folder.not.found=No existe la carpeta {0}. 
jsexception.folder.not.found.at=La carpeta no est\u00e1 en {0}.
jsexception.folder.duplicate.name=Ya existe una carpeta con nombre {0} en {1}.
jsexception.folder.duplicate.label=Etiqueta de carpeta {0} duplicada en carpeta {1}.
jsexception.folder.too.long.uri=La URI de la carpeta es demasiado larga. La longitud m\u00e1xima es de {0} caracteres.

jsexception.got.null.schema.source.wrapper=El subflujo devolvi\u00f3 un contenedor de origen de esquema nulo.
jsexception.got.null.access.grant.source.wrapper=El subflujo devolvi\u00f3 un contenedor de concesi\u00f3n de acceso nulo.
jsexception.got.null.connection.back=El subflujo devolvi\u00f3 una conexi\u00f3n nula.

jsexception.implementation.class.does.not.implement=La clase de implementaci\u00f3n {0} no implementa {1}.
jsexception.implementation.class.not.found=No existe una clase de implementaci\u00f3n para {0}.
jsexception.import.directory.not.found=No existe el directorio de importaci\u00f3n {0}.
jsexception.import.module.not.found=No existe el m\u00f3dulo de importaci\u00f3n {0}.
jsexception.import.multiple.values.for.single.parameter=Se han encontrado varios valores de par\u00e1metro para el par\u00e1metro de valor \u00fanico {0} del informe {1}.
jsexception.input.stream.exhausted=Secuencia de entrada agotada antes de leer {0} bytes.
jsexception.invalid.bean.datasource=Origen de datos bean {0} no v\u00e1lido.
jsexception.invalid.class.attribute.for.model.tag=Atributo de clase no v\u00e1lido para la etiqueta de modelo, recurso {0}.
jsexception.invalid.jdbc.datasource=El origen de datos JDBC {0} no es v\u00e1lido.
jsexception.invalid.aws.datasource=El origen de datos de AWS {0} no es v\u00e1lido.
jsexception.invalid.jndi.jdbc.datasource=Origen de datos JDBC de JNDI {0} no v\u00e1lido.
jsexception.invalid.olap.datasource=Origen de datos OLAP {0} no v\u00e1lido.
jsexception.invalid.resource.reference.source=Origen de referencia de recurso {0} no v\u00e1lido.
jsexception.invalid.session=Sesi\u00f3n actual no v\u00e1lida. Aseg\u00farese de que el servidor se est\u00e1 ejecutando e intente iniciar sesi\u00f3n de nuevo.
jsexception.invalid.uri=La URI {0} no es v\u00e1lida.

jsexception.jar.entry.not.found=No existe una entrada de JAR para la URL {0}.
jsexception.jar.malformed.url=La URL de JAR {0} posee una sintaxis incorrecta.
jsexception.jasperprint.not.found=No existe el objeto de JasperPrint {0}.

jsexception.job.has.more.than.one.trigger=El trabajo {0} tiene m\u00e1s de un desencadenador.
jsexception.job.no.versions.match=La versi\u00f3n {0} del cliente no es la versi\u00f3n m\u00e1s reciente ({1}).
jsexception.job.unknown.calendar.trigger.days.type=Tipo de d\u00edas de desencadenador de calendario desconocido {0}.
jsexception.job.unknown.interval.unit=Unidad de intervalo de trabajo de informe desconocido {0}.
jsexception.job.unknown.start.type=Tipo de inicio de trabajo de informe desconocido {0}.
jsexception.job.unknown.trigger.bean.class=Clase de bean de desencadenador de trabajo de informe desconocida {0}.
jsexception.job.unknown.trigger.type=Tipo de desencadenador de trabajo de informe desconocido {0}.

jsexception.missing.olap.connection=Falta la conexi\u00f3n OLAP.
jsexception.missing.olap.connection.reference=Falta la referencia de conexi\u00f3n OLAP.
jsexception.mondrian.jdbc.datasource.has.an.invalid.type=El origen de datos JDBC de la conexi\u00f3n Mondrian es un tipo no v\u00e1lido ({0}).

jsexception.no.connection.selected=No se ha seleccionado ninguna conexi\u00f3n.
jsexception.no.export.folder.specified=No se ha especificado ninguna carpeta de exportaci\u00f3n.
jsexception.no.export.zip.file.specified=No se ha especificado ning\u00fan archivo ZIP de exportaci\u00f3n.
jsexception.no.import.folder.specified=No se ha especificado ninguna carpeta de importaci\u00f3n.
jsexception.no.import.zip.file.specified=No se ha especificado ning\u00fan archivo ZIP de importaci\u00f3n.
jsexception.no.input.parameter.specified=No se ha especificado ning\u00fan par\u00e1metro de entrada.
jsexception.no.olap.client.connection=No se ha encontrado ninguna conexi\u00f3n de cliente OLAP.
jsexception.no.secure.olap.client.connection=No se ha encontrado ninguna conexi\u00f3n de cliente OLAP segura.
jsexception.no.olap.model.created.for=No se ha creado ning\u00fan modelo OLAP para {0}.
jsexception.no.olap.model.name=No se ha especificado ning\u00fan modelo OLAP.
jsexception.no.olap.model.retrieved=No se ha podido recuperar ning\u00fan modelo OLAP.
jsexception.no.output.parameter.specified=No se ha especificado ning\u00fan par\u00e1metro de salida.
jsexception.no.persistent.class.mapped.to=No se ha asignado ninguna clase persistente a {0}.
jsexception.no.resource.data.provider.found=No se ha encontrado ning\u00fan proveedor de datos de recursos para el ID {0}.
jsexception.no.such.object.permission=El permiso de objeto especificado no existe.
jsexception.no.such.role=No existe la funci\u00f3n {0}.
jsexception.no.such.user=No existe el usuario {0}.
jsexception.no.uri.or.recipient.given=No se ha especificado ning\u00fan URI o destinatario.
jsexception.no.values.to.enumerate=No se han especificado valores que enumerar.
jsexception.no.values.to.enumerate={0} no es un URI de recursos v\u00e1lido.
jsexception.null.uri=URI nulo.

jsexception.output.stream.already.closed=La secuencia de salida ya est\u00e1 cerrada.

jsexception.property.not.a.list=La propiedad {0} del bean {1} no es una propiedad de lista.
jsexception.property.not.a.map=La propiedad {0} del bean {1} no es una propiedad de asignaci\u00f3n.
jsexception.property.not.a.text=La propiedad {0} del bean {1} no es una propiedad de texto.

jsexception.query.datasource.has.an.invalid.type=El origen de datos de la consulta tiene un tipo no v\u00e1lido ({0}).

jsexception.report.job.not.found=No existe un trabajo de informe con el ID {0}.
jsexception.report.resource.already.exists.no.overwrite=El recurso de salida {0} ya existe y el marcador de sobrescritura del trabajo no se ha establecido.
jsexception.report.no.content.resource=El recurso {0} no es un recurso de contenido.
jsexception.report.unit.datasource.has.an.invalid.type=El origen de datos de la unidad de informe tiene un tipo no v\u00e1lido ({0}).
jsexception.report.unknown.output.format=El formato de salida de informe {0} es un formato desconocido.
jsexception.repository.uri.neither.report.nor.folder=El URI de repositorio {0} no es una unidad de informe ni una carpeta.
jsexception.resource.already.exists=El recurso {0} ya existe. Elija un nombre diferente.
jsexception.resource.copyTo.not.implemented=El recurso copyTo no se ha implementado.
jsexception.resource.copyFrom.not.implemented=El recurso copyFrom no se ha implementado.
jsexception.resource.does.not.exist=No existe el recurso {0}.
jsexception.resource.no.match.versions={0}: la versi\u00f3n de cliente {1} no coincide con la versi\u00f3n de repositorio ({2}).
jsexception.resource.of.type.not.found=No se ha encontrado el recurso {0} de tipo {1}.
jsexception.resource.not.report.unit=El recurso {0} no es una unidad de informe.
jsexception.resourcelookup.not.a.resource=ResourceLookup no es un recurso: {0}.
jsexception.folder.delete.root=La carpeta ra\u00edz no se puede eliminar.
jsexception.report.template.not.found=La URI {0} del repositorio no es una plantilla.
jsexception.report.template.uri.not.specified=La URI de plantilla no se especifica.

jsexception.selected.report.not.adhoc=El informe seleccionado no es un informe ad hoc. No se admiten unidades de informes regulares.
jsexception.session.timeout.occurred=Se ha superado el tiempo de espera de la sesi\u00f3n OLAP.

jsexception.too.many.data.rows=Fallo del exportador debido a demasiadas filas de datos. Puede cambiar los ajustes del exportador para  tener una p\u00e1gina por hoja.

jsexception.unable.to.complete.request=El sistema no ha podido completar su solicitud. Puede que su conversaci\u00f3n haya finalizado, caducado o haya sido invalidada.
jsexception.undefined.file.type=No se reconoce este tipo de archivo.
jsexception.unknown.connection.type=No se reconoce este tipo de conexi\u00f3n.
jsexception.unknown.parameter.type.for.multiple.value.input=El tipo de par\u00e1metro {0} no es v\u00e1lido para una entrada de varios valores.
jsexception.unknown.permission.recipient.type=No se reconoce el tipo de destinatario de permiso {0}.
jsexception.unknown.property.filter.operation=No se reconoce la operaci\u00f3n de filtro de propiedades {0}.
jsexception.unknown.timezone=No se reconoce la zona horaria {0}. 
jsexception.uri.not.found=URI {0} no encontrado en el repositorio.
jsexception.user.credentials.are.expired=Las credenciales del usuario {0} han caducado.
jsexception.user.disabled=El usuario {0} est\u00e1 deshabilitado.
jsexception.user.expired=El usuario {0} ha caducado.
jsexception.user.locked=El usuario {0} est\u00e1 bloqueado.
jsexception.user.not.found=No existe el usuario {0}.

jsexception.move.folder.source.uri.ancestor.destination={0} no se puede mover a {1}. El destino es un elemento secundario del origen.
jsexception.move.folder.to.same.folder=No puede mover la carpeta {0} a la misma carpeta {1}.
jsexception.move.resource.to.same.folder=No puede mover el recurso {0} a la misma carpeta {1}.
jsexception.move.folder.path.already.exists=No puede mover la carpeta {0} a {1}. La carpeta de destino ya contiene un objeto con el mismo nombre.
jsexception.move.resource.path.already.exists=No puede mover el recurso {0} a {1}. El destino ya contiene un objeto con el mismo nombre.
jsexception.copy.resource.referenced.not.readable=Otro recurso hace referencia al recurso {0}, pero no se puede leer.
jsexception.copy.resource.circular.reference=Se ha detectado una referencia circular para el recurso {0}.
jsexception.folder.moved=La carpeta {0} se ha movido a {1}.

report.scheduling.error.filling.report=No se complet\u00f3 el informe. Se produjo un error al ejecutarlo.
report.scheduling.error.exporting.report=No se complet\u00f3 la exportaci\u00f3n a {0}. Un error ha interrumpido el proceso.
report.scheduling.error.saving.to.repository={0} no se ha guardado en el repositorio. Un error ha interrumpido el proceso.
report.scheduling.error.sending.email.notification=No se complet\u00f3 la notificaci\u00f3n de error de trabajo. Se produjo un error al enviarlo.
report.scheduling.error.system=No se complet\u00f3 el trabajo. Se produjo un error del sistema al ejecutarlo.

exception.report.unrecognized.number.type=Tipo num\u00e9rico no reconocido {0}
exception.report.unrecognized.date.type=Tipo de fecha/hora no reconocido {0}
exception.report.unsupported.date.input.value=No puede convertir el valor de entrada {0} del tipo {1} en un par\u00e1metro de fecha/hora.
exception.report.unsupported.date.parameter.type=Tipo de fecha/hora no admitido {0}
exception.report.unsupported.input.control.data.type=No se admite el tipo de datos de control de entrada {0}.

jsexception.view.report.could.not.load=La unidad de informe no existe o no se puede cargar.
jsexception.view.page.does.not.exist=No se ha encontrado la p\u00e1gina {0} en el informe
jsexception.view.report.error=Se ha producido un error durante la generaci\u00f3n del informe
jsexception.export.unknown.argument=No se reconoce la opci\u00f3n {0}.

jsexception.mondrian.no.connection.for.resource=No hay ninguna conexi\u00f3n Mondrian para el recurso {0}.

jsexception.target.org.not.found=No se ha encontrado la organizaci\u00f3n de destino {0} en el repositorio.
jsexception.template.folder.not.found=No se ha encontrado la carpeta de plantilla en el repositorio.

jsexception.search.duplicate.label=Ya existe un objeto con la etiqueta {0} en la carpeta {1}.
jsexception.search.duplicate.name=Ya existe un objeto con el nombre {0} en la carpeta {1}.

report.scheduling.error.saving.data.snapshot.disabled=Guardar datos de inst\u00e1ntaneas est\u00e1 desactivado.
report.scheduling.error.data.snapshot.not.populated=No se han propagado los datos de instant\u00e1nea.
report.scheduling.error.data.snapshot.not.persistable=No se pueden guardar los datos de instant\u00e1nea.
report.scheduling.error.saving.data.snapshot.failed=Se ha producido un error al guardar los datos de la instant\u00e1nea.

exception.remote.resource.already.exists=El recurso {0} ya existe.
exception.remote.resource.not.found=No se ha encontrado el recurso {0}
exception.remote.resource.type.not.supported=El tipo de recurso {0} no es compatible con esta operaci\u00f3n.
exception.remote.folder.not.found=No se encuentra la carpeta {0} o no es una carpeta.
exception.remote.unexpected.error=Error inesperado.
exception.remote.weak.password=Contrase\u00f1a poco segura.
exception.remote.resource.not.ready=La tarea {0} no ha finalizado a\u00fan.
exception.remote.no.such.export.process=No hay ninguna tarea de exportaci\u00f3n con el id {0}.
exception.remote.no.such.import.process=No hay ninguna tarea de exportaci\u00f3n con el id {0}.
exception.remote.access.denied=Acceso denegado
exception.remote.modification.not.allowed=No se permite la modificaci\u00f3n del recurso {0}.
exception.remote.illegal.parameter.value.error=El valor "{1}" del par\u00e1metro "{0}" no es v\u00e1lido.
exception.remote.mandatory.parameter.error=Falta el par\u00e1metro obligatorio "{0}".
exception.remote.import.failed=Error de importaci\u00f3n. Raz\u00f3n: {0}
exception.remote.import.failed.zip.error=Error de importaci\u00f3n. Raz\u00f3n: no se puede leer el archivo comprimido.
exception.remote.import.failed.content.error=Error de importaci\u00f3n. Motivo: el archivo zip proporcionado no es un archivo de exportaci\u00f3n de JasperReports Server v\u00e1lido.
exception.remote.resource.querying.not.supported=El recurso {0} no es compatible con las consultas
exception.remote.version.not.match=Error en la actualizaci\u00f3n: las versiones no coinciden

#AWS data source specific exception messages
aws.exception.datasource.recovery.base=Se ha producido una excepci\u00f3n durante la recuperaci\u00f3n del origen de datos de AWS: {0}.
aws.exception.datasource.recovery.timeout=Es posible que haya un problema con la URL de JDBC, la configuraci\u00f3n de seguridad de AWS o el proceso de recuperaci\u00f3n del origen de datos de AWS, lo cual puede llevar hasta 2 minutos.
aws.exception.datasource.recovery.instance.not.active=La instancia del origen de datos de AWS no est\u00e1 activa.
aws.exception.datasource.recovery.is.not.possible=El origen de datos de AWS no se puede recuperar autom\u00e1ticamente dado que JasperReports Server y la instancia de la base de datos no se encuentran en el mismo VPC.
aws.exception.datasource.recovery.public.ip.not.provided=Debe especificar la "IP p\u00fablica de ingreso" de este servidor en la configuraci\u00f3n de AWS para utilizar la instalaci\u00f3n y recuperaci\u00f3n autom\u00e1ticas del origen de datos de AWS.
aws.exception.datasource.recovery.public.ip.not.determined=No se puede determinar la direcci\u00f3n IP de la instancia para la recuperaci\u00f3n del origen de datos de AWS.
aws.exception.datasource.load.default.credentials=Esta instancia no puede utilizar <b>las credenciales de la instancia de EC2</b> para conectarse autom\u00e1ticamente a Amazon RDS y Amazon Redshift porque no tiene funci\u00f3n de Administraci\u00f3n de identidad y acceso (IAM) asignada. Lea <a class='launcher inline' href='http://community.jaspersoft.com/jaspersoft-aws/launch' target='_blank'>C\u00f3mo lanzar Jaspersoft para AWS</a> para saber c\u00f3mo lanzar un servidor que es capaz de conectarse autom\u00e1ticamente a or\u00edgenes de datos AWS de forma segura.<br><br>Como soluci\u00f3n alternativa, puede usar <b>las credenciales de AWS</b>.
aws.exception.datasource.rds.vpc.recovery=No se puede asignar autom\u00e1ticamente el grupo de seguridad de VPC denominado {0} a la instancia de RDS {1}. La operaci\u00f3n actualmente no es compatible con la API de AWS. Asigne de forma manual el grupo de seguridad a la instancia de RDS.
aws.exception.datasource.accessKey.invalid=La clave de acceso de AWS no es v\u00e1lida.
aws.exception.datasource.secretKey.invalid=La clave secreta de AWS no es v\u00e1lida.

#Cluster specific exception messages
cluster.exception.session.attribute.missing=Se ha producido un error no relacionado en el servidor. Su sesi\u00f3n se ha reiniciado, pero se ha perdido el trabajo que no se haya guardado. Disculpe la molestia.<p><p>Haga clic en el siguiente enlace para volver a la p\u00e1gina de inicio y empezar de nuevo: <a class="launcher inline" href="home.html">Ir a la p\u00e1gina de inicio</a>. Si se produce otro error, p\u00f3ngase en contacto con su administrador.
cluster.exception.session.attribute.missing.popup=Se ha producido un error no relacionado en el servidor. Su sesi\u00f3n se ha reiniciado, pero se ha perdido el trabajo que no se haya guardado. Disculpe la molestia.<p><p>Haga clic en el siguiente bot\u00f3n para volver a la p\u00e1gina de inicio y empezar de nuevo. Si se produce otro error, p\u00f3ngase en contacto con su administrador.