jsexception.access.denied=Voc\u00ea n\u00e3o tem permiss\u00e3o para realizar a a\u00e7\u00e3o solicitada. Fa\u00e7a login como um usu\u00e1rio com permiss\u00e3o, se for poss\u00edvel.
jsexception.any={0}

jsexception.bean.has.no.method=Bean com o nome {0} n\u00e3o tem m\u00e9todo {1}.
jsexception.bean.name.not.found.for.interface=Nenhum nome de bean foi encontrada para a interface {0}.
jsexception.bean.no.name=N\u00e3o \u00e9 poss\u00edvel encontrar um bean com o nome {0}.
jsexception.bean.not.a.ReportDataSourceService=O bean {0} n\u00e3o \u00e9 ReportDataSourceService.

jsexception.call.not.supported=A chamada n\u00e3o \u00e9 suportada por objetos de pesquisa de recursos.
jsexception.connection.type.not.suported=O tipo de conex\u00e3o n\u00e3o est\u00e1 suportado.
jsexception.connection.uri.not.specified=URI de conex\u00e3o n\u00e3o foi especificado.
jsexception.could.not.find.resource.with.uri=O recurso com URI {0} n\u00e3o pode ser encontrado. 
jsexception.could.not.find.content.resource.with.uri=O recurso de conte\u00fado com URI {0} n\u00e3o pode ser encontrado.
jsexception.unexpected.resource.type.at.uri=Tipo inesperado ({0}) do recurso com URI {1} 

jsexception.default.message=Ocorreu um erro inexplic\u00e1vel. Entre em contato com o administrador do sistema.

jsexception.error.creating.connection=Ocorreu um erro durante a cria\u00e7\u00e3o da conex\u00e3o. Tente novamente.
jsexception.parameter.has.multiple.values=Par\u00e2metro {0} tem v\u00e1rios valores.

jsexception.parameter.has.no.value=Par\u00e2metro {0} n\u00e3o tem nenhum valor.


jsexception.failed.to.create.connection=N\u00e3o foi poss\u00edvel criar conex\u00e3o.
jsexception.failed.to.save.connection=A conex\u00e3o n\u00e3o foi salva.
jsexception.failed.to.save.connection.changes=As altera\u00e7\u00f5es de conex\u00e3o n\u00e3o foram salvas.
jsexception.file.resource.is.reference=Recurso do arquivo {0} \u00e9 uma refer\u00eancia e n\u00e3o tem dados.
jsexception.file.resource.no.match.type=O tipo declarado do recurso ({0}) n\u00e3o corresponde ao tipo da refer\u00eancia ({1}).
jsexception.folder.already.exists=J\u00e1 existe uma pasta com o nome {0}. Escolha um nome diferente.
jsexception.folder.details.not.found=Detalhes de pasta {0} n\u00e3o foram encontrados nas informa\u00e7\u00f5es de importa\u00e7\u00e3o. 
jsexception.folder.not.found=A pasta {0} n\u00e3o pode ser encontrada. 
jsexception.folder.not.found.at=A pasta n\u00e3o est\u00e1 em {0}.
jsexception.folder.duplicate.name=J\u00e1 existe uma pasta chamada {0} em {1}.
jsexception.folder.duplicate.label=T\u00edtulo de pasta {0} duplicado na pasta {1}.
jsexception.folder.too.long.uri=O URI da pasta \u00e9 muito longo. O comprimento m\u00e1ximo \u00e9 {0} caracteres.

jsexception.got.null.schema.source.wrapper=O subfluxo retornou um empacotador de fonte de esquema nulo.
jsexception.got.null.access.grant.source.wrapper=O subfluxo retornou um empacotador de fonte de concess\u00e3o de acesso nulo.
jsexception.got.null.connection.back=O subfluxo retornou uma liga\u00e7\u00e3o nula.

jsexception.implementation.class.does.not.implement=Classe de implementa\u00e7\u00e3o {0} n\u00e3o implementa {1}.
jsexception.implementation.class.not.found=Uma classe de implementa\u00e7\u00e3o de {0} n\u00e3o pode ser encontrada.
jsexception.import.directory.not.found=Diret\u00f3rio da importa\u00e7\u00e3o {0} n\u00e3o pode ser encontrado.
jsexception.import.module.not.found=O m\u00f3dulo da importa\u00e7\u00e3o {0} n\u00e3o pode ser encontrado.
jsexception.import.multiple.values.for.single.parameter=V\u00e1rios valores de par\u00e2metro foram encontrados para o par\u00e2metro de valor \u00fanico {0} do relat\u00f3rio {1}.
jsexception.input.stream.exhausted=O fluxo de entrada foi esgotado antes de ler {0} bytes.
jsexception.invalid.bean.datasource=A fonte de dados de bean {0} \u00e9 inv\u00e1lida.
jsexception.invalid.class.attribute.for.model.tag=O atributo de classe para tag do modelo, recurso {0}, \u00e9 inv\u00e1lido.
jsexception.invalid.jdbc.datasource=A fonte de dados de JDBC {0} \u00e9 inv\u00e1lida.
jsexception.invalid.aws.datasource=A fonte de dados AWS {0} \u00e9 inv\u00e1lida.
jsexception.invalid.jndi.jdbc.datasource=A fonte de dados JNDI JDBC {0} \u00e9 inv\u00e1lida.
jsexception.invalid.olap.datasource=A fonte de dados de OLAP {0} \u00e9 inv\u00e1lida.
jsexception.invalid.resource.reference.source=A fonte de refer\u00eancia {0} do recurso \u00e9 inv\u00e1lido.
jsexception.invalid.session=A sess\u00e3o atual \u00e9 inv\u00e1lida. Verifique se o servidor est\u00e1 em execu\u00e7\u00e3o e tente efetuar login novamente.
jsexception.invalid.uri=URI {0} \u00e9 inv\u00e1lido.

jsexception.jar.entry.not.found=Uma entrada JAR para URL {0} n\u00e3o pode ser encontrada.
jsexception.jar.malformed.url=URL de JAR {0} tem sintaxe incorreta.
jsexception.jasperprint.not.found=O objeto JasperPrint {0} n\u00e3o pode ser encontrado.

jsexception.job.has.more.than.one.trigger=Trabalho {0} tem mais de um acionador.
jsexception.job.no.versions.match=Vers\u00e3o de cliente {0} n\u00e3o \u00e9 a vers\u00e3o mais recente ({1}).
jsexception.job.unknown.calendar.trigger.days.type=Tipo desconhecido de dias do acionador de calend\u00e1rio {0}.
jsexception.job.unknown.interval.unit=Unidade de intervalo de trabalho de relat\u00f3rio desconhecida {0}.
jsexception.job.unknown.start.type=Tipo desconhecido de in\u00edcio de trabalho de relat\u00f3rio {0}.
jsexception.job.unknown.trigger.bean.class=Classe de bean desconhecida do acionador do trabalho de relat\u00f3rio {0}.
jsexception.job.unknown.trigger.type=Tipo desconhecido de acionador do trabalho de relat\u00f3rio {0}.

jsexception.missing.olap.connection=A conex\u00e3o OLAP est\u00e1 ausente.
jsexception.missing.olap.connection.reference=A refer\u00eancia de conex\u00e3o OLAP est\u00e1 ausente.
jsexception.mondrian.jdbc.datasource.has.an.invalid.type=A fonte de dados JDBC da conex\u00e3o Mondrian \u00e9 um tipo inv\u00e1lido ({0}).

jsexception.no.connection.selected=Nenhuma conex\u00e3o selecionada.
jsexception.no.export.folder.specified=Nenhuma pasta de exporta\u00e7\u00e3o especificada.
jsexception.no.export.zip.file.specified=Nenhum arquivo ZIP de exporta\u00e7\u00e3o especificado.
jsexception.no.import.folder.specified=Nenhuma pasta de importa\u00e7\u00e3o especificada.
jsexception.no.import.zip.file.specified=Nenhum arquivo ZIP de importa\u00e7\u00e3o especificado.
jsexception.no.input.parameter.specified=Nenhum par\u00e2metro de entrada especificado.
jsexception.no.olap.client.connection=Nenhuma conex\u00e3o de cliente OLA encontrada.
jsexception.no.secure.olap.client.connection=Nenhuma conex\u00e3o de cliente OLA segura encontrada.
jsexception.no.olap.model.created.for=Nenhum modelo OLAP criado para {0}.
jsexception.no.olap.model.name=Nenhum modelo OLAP especificado.
jsexception.no.olap.model.retrieved=Nenhum modelo OLAP pode ser recuperado.
jsexception.no.output.parameter.specified=Nenhum par\u00e2metro de sa\u00edda especificado.
jsexception.no.persistent.class.mapped.to=Nenhuma classe persistente est\u00e1 mapeada para {0}.
jsexception.no.resource.data.provider.found=Nenhum provedor de dados de recurso encontrado para ID {0}.
jsexception.no.such.object.permission=A permiss\u00e3o do objeto especificado n\u00e3o existe.
jsexception.no.such.role=N\u00e3o existe fun\u00e7\u00e3o {0}.
jsexception.no.such.user=N\u00e3o existe usu\u00e1rio {0}.
jsexception.no.uri.or.recipient.given=Nenhum URI ou recipiente especificado.
jsexception.no.values.to.enumerate=Nenhum valor especificado para enumera\u00e7\u00e3o.
jsexception.no.values.to.enumerate={0} n\u00e3o \u00e9 um URI de recurso v\u00e1lido.
jsexception.null.uri=URI nulo.

jsexception.output.stream.already.closed=O fluxo de sa\u00edda j\u00e1 est\u00e1 fechado.

jsexception.property.not.a.list=Propriedade {0} do bean {1} n\u00e3o \u00e9 uma propriedade de lista.
jsexception.property.not.a.map=Propriedade {0} do bean {1} n\u00e3o \u00e9 uma propriedade de mapa.
jsexception.property.not.a.text=Propriedade {0} do bean {1} n\u00e3o \u00e9 uma propriedade de texto.

jsexception.query.datasource.has.an.invalid.type=A fonte de dados de consulta tem um tipo inv\u00e1lido ({0}).

jsexception.report.job.not.found=Um trabalho de relat\u00f3rio com ID {0} n\u00e3o pode ser encontrado.
jsexception.report.resource.already.exists.no.overwrite=Recurso de sa\u00edda {0} j\u00e1 existe e a bandeira de substitui\u00e7\u00e3o do trabalho n\u00e3o est\u00e1 definida.
jsexception.report.no.content.resource=Recurso {0} n\u00e3o \u00e9 um recurso de conte\u00fado.
jsexception.report.unit.datasource.has.an.invalid.type=A fonte de dados de unidade de relat\u00f3rio tem um tipo inv\u00e1lido ({0}).
jsexception.report.unknown.output.format=Formato de sa\u00edda do relat\u00f3rio {0} n\u00e3o \u00e9 um formato conhecido.
jsexception.repository.uri.neither.report.nor.folder=URI do reposit\u00f3rio {0} n\u00e3o \u00e9 uma unidade de relat\u00f3rio nem uma pasta.
jsexception.resource.already.exists=Recurso {0} j\u00e1 existe. Escolha um nome diferente.
jsexception.resource.copyTo.not.implemented=copyTo do recurso n\u00e3o est\u00e1 implementado.
jsexception.resource.copyFrom.not.implemented=copyFrom do recurso n\u00e3o est\u00e1 implementado.
jsexception.resource.does.not.exist=Recurso {0} n\u00e3o existe.
jsexception.resource.no.match.versions={0}: cliente vers\u00e3o {1} n\u00e3o corresponde \u00e0 vers\u00e3o do reposit\u00f3rio ({2}).
jsexception.resource.of.type.not.found=Recurso {0} do tipo {1} n\u00e3o pode ser encontrado.
jsexception.resource.not.report.unit=Recurso {0} n\u00e3o \u00e9 uma unidade de relat\u00f3rio.
jsexception.resourcelookup.not.a.resource=ResourceLookup n\u00e3o \u00e9 um recurso: {0}.
jsexception.folder.delete.root=A pasta raiz n\u00e3o pode ser exclu\u00edda.
jsexception.report.template.not.found=O URI do reposit\u00f3rio {0} n\u00e3o \u00e9 modelo.
jsexception.report.template.uri.not.specified=URI de modelo n\u00e3o foi especificado.

jsexception.selected.report.not.adhoc=O relat\u00f3rio selecionado n\u00e3o \u00e9 um relat\u00f3rio Ad Hoc. Unidades de relat\u00f3rios regulares n\u00e3o s\u00e3o suportadas.
jsexception.session.timeout.occurred=A sess\u00e3o de OLAP expirou.

jsexception.too.many.data.rows=O exportador do Excel falhou devido ao excesso de linhas de dados. Voc\u00ea pode alterar as configura\u00e7\u00f5es do exportador para uma p\u00e1gina por folha.

jsexception.unable.to.complete.request=O sistema n\u00e3o conseguiu concluir sua solicita\u00e7\u00e3o. Sua conversa terminou, expirou, ou foi invalidada.
jsexception.undefined.file.type=O tipo de arquivo n\u00e3o \u00e9 reconhecido.
jsexception.unknown.connection.type=O tipo de conex\u00e3o n\u00e3o foi reconhecido.
jsexception.unknown.parameter.type.for.multiple.value.input=O tipo de par\u00e2metro {0} n\u00e3o \u00e9 v\u00e1lido para a entrada de v\u00e1rios valores.
jsexception.unknown.permission.recipient.type=Tipo de recipiente de permiss\u00e3o {0} n\u00e3o \u00e9 reconhecido.
jsexception.unknown.property.filter.operation=Opera\u00e7\u00e3o do filtro de propriedade {0} n\u00e3o \u00e9 reconhecida.
jsexception.unknown.timezone=Fuso hor\u00e1rio {0} n\u00e3o \u00e9 reconhecido 
jsexception.uri.not.found=URI {0} n\u00e3o pode ser encontrado no reposit\u00f3rio.
jsexception.user.credentials.are.expired=Credenciais do usu\u00e1rio {0} expiraram.
jsexception.user.disabled=Usu\u00e1rio {0} est\u00e1 desativado.
jsexception.user.expired=Usu\u00e1rio {0} expirou.
jsexception.user.locked=Usu\u00e1rio {0} est\u00e1 bloqueado.
jsexception.user.not.found=Usu\u00e1rio {0} n\u00e3o pode ser encontrado.

jsexception.move.folder.source.uri.ancestor.destination={0} n\u00e3o pode ser movido para {1}. O destino \u00e9 um filho da fonte.
jsexception.move.folder.to.same.folder=N\u00e3o \u00e9 poss\u00edvel mover pasta {0} para a mesma pasta {1}.
jsexception.move.resource.to.same.folder=N\u00e3o \u00e9 poss\u00edvel mover recurso {0} para a mesma pasta {1}.
jsexception.move.folder.path.already.exists=N\u00e3o \u00e9 poss\u00edvel mover pasta {0} para {1}. A pasta de destino j\u00e1 cont\u00e9m um objeto com o mesmo nome.
jsexception.move.resource.path.already.exists=N\u00e3o \u00e9 poss\u00edvel mover recurso {0} para {1}. O destino j\u00e1 cont\u00e9m um objeto com o mesmo nome.
jsexception.copy.resource.referenced.not.readable=Recurso {0} \u00e9 referenciado por outro recurso, mas n\u00e3o \u00e9 leg\u00edvel.
jsexception.copy.resource.circular.reference=Foi detectada um refer\u00eancia circular para recurso {0}.
jsexception.folder.moved=Pasta {0} foi movida para {1}.

report.scheduling.error.filling.report=O relat\u00f3rio n\u00e3o foi conclu\u00eddo. Ocorreu um erro ao execut\u00e1-lo.
report.scheduling.error.exporting.report=Exporta\u00e7\u00e3o para {0} n\u00e3o foi conclu\u00edda. Um erro interrompeu o processo.
report.scheduling.error.saving.to.repository={0} n\u00e3o foi salvo em um reposit\u00f3rio. Um erro interrompeu o processo.
report.scheduling.error.sending.email.notification=A notifica\u00e7\u00e3o de erro de trabalho n\u00e3o foi conclu\u00edda. Ocorreu um erro durante o envio.
report.scheduling.error.system=O trabalho n\u00e3o foi conclu\u00eddo. Ocorreu um erro do sistema ao execut\u00e1-lo.

exception.report.unrecognized.number.type=Tipo num\u00e9rico desconhecido {0}
exception.report.unrecognized.date.type=Tipo de data/hora desconhecido {0}
exception.report.unsupported.date.input.value=N\u00e3o \u00e9 poss\u00edvel converter o valor de entrada {0} do tipo {1} para um par\u00e2metro de data/hora.
exception.report.unsupported.date.parameter.type=Tipo de data/hora n\u00e3o suportado {0}
exception.report.unsupported.input.control.data.type=Tipo de dados da entrada de controle {0} n\u00e3o \u00e9 suportado.

jsexception.view.report.could.not.load=A unidade do relat\u00f3rio n\u00e3o pode ser encontrada ou n\u00e3o pode ser carregada.
jsexception.view.page.does.not.exist=P\u00e1gina {0} n\u00e3o encontrada no relat\u00f3rio
jsexception.view.report.error=Ocorreu um erro durante a gera\u00e7\u00e3o do relat\u00f3rio
jsexception.export.unknown.argument=Op\u00e7\u00e3o {0} n\u00e3o \u00e9 reconhecida.

jsexception.mondrian.no.connection.for.resource=N\u00e3o existe conex\u00e3o Mondrian para recurso {0}.

jsexception.target.org.not.found=Organiza\u00e7\u00e3o alvo {0} n\u00e3o pode ser encontrada no reposit\u00f3rio.
jsexception.template.folder.not.found=N\u00e3o foi poss\u00edvel localizar a pasta de modelos no reposit\u00f3rio.

jsexception.search.duplicate.label=J\u00e1 existe um objeto com o t\u00edtulo {0} na pasta {1}.
jsexception.search.duplicate.name=J\u00e1 existe um objeto com o nome {0} na pasta {1}.

report.scheduling.error.saving.data.snapshot.disabled=Grava\u00e7\u00e3o de instant\u00e2neo de dados desativada.
report.scheduling.error.data.snapshot.not.populated=Instant\u00e2neo de dados n\u00e3o foi preenchido.
report.scheduling.error.data.snapshot.not.persistable=Instant\u00e2neo de dados n\u00e3o pode ser salvo.
report.scheduling.error.saving.data.snapshot.failed=Erro ao salvar instant\u00e2neo de dados.

exception.remote.resource.already.exists=Recurso {0} j\u00e1 existe.
exception.remote.resource.not.found=Recurso {0} n\u00e3o encontrado.
exception.remote.resource.type.not.supported=Tipo de recurso {0} n\u00e3o \u00e9 suportado por esta opera\u00e7\u00e3o.
exception.remote.folder.not.found=Pasta {0} n\u00e3o foi encontrada ou n\u00e3o \u00e9 uma pasta.
exception.remote.unexpected.error=Erro inesperado.
exception.remote.weak.password=Senha fraca.
exception.remote.resource.not.ready=Tarefa {0} ainda n\u00e3o terminada.
exception.remote.no.such.export.process=Nenhuma tarefa de exporta\u00e7\u00e3o com id {0}.
exception.remote.no.such.import.process=Nenhuma tarefa de importa\u00e7\u00e3o com id {0}.
exception.remote.access.denied=Acesso negado.
exception.remote.modification.not.allowed=Modifica\u00e7\u00e3o do recurso {0} n\u00e3o \u00e9 permitida.
exception.remote.illegal.parameter.value.error=Valor do par\u00e2metro "{1}" do par\u00e2metro "{0}" \u00e9 inv\u00e1lido.
exception.remote.mandatory.parameter.error=Par\u00e2metro obrigat\u00f3rio "{0}" est\u00e1 ausente.
exception.remote.import.failed=Falha na importa\u00e7\u00e3o. Motivo: {0}
exception.remote.import.failed.zip.error=Falha na importa\u00e7\u00e3o. Motivo: n\u00e3o \u00e9 poss\u00edvel ler o arquivo zip.
exception.remote.import.failed.content.error=Falha na importa\u00e7\u00e3o. Motivo: arquivo zip fornecido n\u00e3o \u00e9 arquivo de exporta\u00e7\u00e3o de Jasper Server v\u00e1lido.
exception.remote.resource.querying.not.supported=Recurso {0} n\u00e3o tem suporte para consultas
exception.remote.version.not.match=Falha na atualiza\u00e7\u00e3o: vers\u00f5es n\u00e3o correspondem

#AWS data source specific exception messages
aws.exception.datasource.recovery.base=Ocorreu uma exce\u00e7\u00e3o durante a recupera\u00e7\u00e3o da fonte de dados AWS: {0}.
aws.exception.datasource.recovery.timeout=Pode haver um problema com a URL de JDBC, Configura\u00e7\u00f5es de Seguran\u00e7a de AWS ou o processo de recupera\u00e7\u00e3o de Fonte de dados AWS, que pode levar at\u00e9 2 minutos.
aws.exception.datasource.recovery.instance.not.active=A inst\u00e2ncia de fonte de dados AWS n\u00e3o est\u00e1 ativa.
aws.exception.datasource.recovery.is.not.possible=A fonte de dados AWS n\u00e3o pode ser recuperada automaticamente, pois seu JasperReports Server e a inst\u00e2ncia de banco de dados n\u00e3o est\u00e3o localizados no mesmo VPC.
aws.exception.datasource.recovery.public.ip.not.provided=Voc\u00ea deve fornecer o 'IP P\u00fablico de Ingresso' deste servidor em Configura\u00e7\u00f5es de AWS para usar configura\u00e7\u00e3o e recupera\u00e7\u00e3o autom\u00e1tica de Fonte de dados AWS.
aws.exception.datasource.recovery.public.ip.not.determined=N\u00e3o foi poss\u00edvel determinar o endere\u00e7o IP da inst\u00e2ncia para a recupera\u00e7\u00e3o de Fonte de Dados AWS.
aws.exception.datasource.load.default.credentials=Essa inst\u00e2ncia n\u00e3o pode usar <b>credenciais da inst\u00e2ncia EC2</b> para se conectar automaticamente a Amazon RDS e Amazon Redshift, porque n\u00e3o tem atribu\u00edda uma Fun\u00e7\u00e3o de Gerenciamento de Acesso e Identidade (Identity and Access Management - IAM). Leia <a class='launcher inline' href='http://community.jaspersoft.com/jaspersoft-aws/launch' target='_blank'>Como Iniciar Jaspersoft para AWS</a> para aprender como iniciar um servidor que pode conectar automaticamente e com seguran\u00e7a a fontes de dados AWS.<br><br>Como alternativa voc\u00ea pode usar <b>credenciais AWS</b>.
aws.exception.datasource.rds.vpc.recovery=N\u00e3o \u00e9 poss\u00edvel atribuir automaticamente o grupo de seguran\u00e7a VPC chamado {0} a inst\u00e2ncia de RDS {1}. A opera\u00e7\u00e3o n\u00e3o \u00e9 suportada por AWS API atualmente. Por favor atribuir manualmente o grupo de seguran\u00e7a para sua inst\u00e2ncia de RDS.
aws.exception.datasource.accessKey.invalid=Chave de acesso AWS \u00e9 inv\u00e1lida.
aws.exception.datasource.secretKey.invalid=Chave secreta AWS \u00e9 inv\u00e1lida.

#Cluster specific exception messages
cluster.exception.session.attribute.missing=Um erro n\u00e3o relacionado ocorreu no servidor. Sua sess\u00e3o foi reiniciada, mas o trabalho n\u00e3o salvo foi perdido. Por favor, desculpe o transtorno.<p><p>Clique no link abaixo para voltar para a p\u00e1gina inicial e come\u00e7ar de novo: <a class="launcher inline" href="home.html">Ir \u00e0 p\u00e1gina inicial</a>. Se voc\u00ea encontrar outro erro, entre em contato com o administrador.
cluster.exception.session.attribute.missing.popup=Um erro n\u00e3o relacionado ocorreu no servidor. Sua sess\u00e3o foi reiniciada, mas o trabalho n\u00e3o salvo foi perdido. Por favor, desculpe o transtorno.<p><p>Clique no bot\u00e3o abaixo para voltar para a p\u00e1gina inicial e come\u00e7ar de novo. Se voc\u00ea encontrar outro erro, entre em contato com o administrador.