jsexception.access.denied=Vous n\u2019\u00eates pas autoris\u00e9 \u00e0 effectuer l\u2019action demand\u00e9e. Connectez-vous avec un compte d\u2019utilisateur autoris\u00e9, si cela est possible.
jsexception.any={0}

jsexception.bean.has.no.method=Le Bean {0} ne comporte pas de m\u00e9thode {1}.
jsexception.bean.name.not.found.for.interface=Aucun nom de Bean trouv\u00e9 pour l\u2019interface {0}.
jsexception.bean.no.name=Impossible de trouver un Bean portant le nom {0}.
jsexception.bean.not.a.ReportDataSourceService=Le Bean {0} n\u2019est pas un ReportDataSourceService.

jsexception.call.not.supported=L\u2019appel n\u2019est pas pris en charge par les objets de consultation de ressources.
jsexception.connection.type.not.suported=Le type de connexion n\u2019est pas pris en charge.
jsexception.connection.uri.not.specified=L\u2019URI de connexion n\u2019est pas sp\u00e9cifi\u00e9.
jsexception.could.not.find.resource.with.uri=Impossible de trouver la ressource associ\u00e9e \u00e0 l\u2019URI {0}. 
jsexception.could.not.find.content.resource.with.uri=Impossible de trouver la ressource de contenu associ\u00e9e \u00e0 l\u2019URI {0}.
jsexception.unexpected.resource.type.at.uri=Type inattendu ({0}) de la ressource avec l''URI {1} 

jsexception.default.message=Une erreur inexpliqu\u00e9e s\u2019est produite. Contacter votre administrateur syst\u00e8me.

jsexception.error.creating.connection=Une erreur s\u2019est produite pendant la cr\u00e9ation de la connexion. Veuillez r\u00e9essayer.
jsexception.parameter.has.multiple.values=Le param\u00e8tre {0} poss\u00e8de plusieurs valeurs.

jsexception.parameter.has.no.value=Le param\u00e8tre {0} ne comporte aucune valeur.


jsexception.failed.to.create.connection=Impossible d\u2019\u00e9tablir la connexion.
jsexception.failed.to.save.connection=La connexion n\u2019a pas \u00e9t\u00e9 enregistr\u00e9e.
jsexception.failed.to.save.connection.changes=Les modifications apport\u00e9es \u00e0 la connexion n\u2019ont pas \u00e9t\u00e9 enregistr\u00e9es.
jsexception.file.resource.is.reference=La ressource de fichier {0} est une r\u00e9f\u00e9rence et ne contient aucune donn\u00e9e.
jsexception.file.resource.no.match.type=Le type d\u00e9clar\u00e9 de la ressource ({0}) ne correspond pas au type de r\u00e9f\u00e9rence r\u00e9el ({1}).
jsexception.folder.already.exists=Un dossier portant le nom {0} existe d\u00e9j\u00e0. Entrer un autre nom.
jsexception.folder.details.not.found=Les d\u00e9tails du dossier {0} sont introuvables dans les informations d\u2019importation. 
jsexception.folder.not.found=Impossible de trouver le dossier {0}. 
jsexception.folder.not.found.at=Le dossier n\u2019est pas \u00e0 {0}.
jsexception.folder.duplicate.name=Un dossier portant le nom {0} existe d\u00e9j\u00e0 dans {1}.
jsexception.folder.duplicate.label=Le libell\u00e9 {0} est en double dans le dossier {1}.
jsexception.folder.too.long.uri=L''URI du dossier est trop long. La longueur maximale est de {0} caract\u00e8res.

jsexception.got.null.schema.source.wrapper=Le subflow a renvoy\u00e9 une classe enveloppante de source de sch\u00e9ma nulle.
jsexception.got.null.access.grant.source.wrapper=Le subflow a renvoy\u00e9 une classe enveloppante de source d\u2019autorisation d\u2019acc\u00e8s nulle.
jsexception.got.null.connection.back=Le subflow a renvoy\u00e9 une connexion nulle.

jsexception.implementation.class.does.not.implement=La classe d\u2019impl\u00e9mentation {0} n\u2019int\u00e8gre pas {1}.
jsexception.implementation.class.not.found=Impossible de trouver la classe d\u2019impl\u00e9mentation pour {0}.
jsexception.import.directory.not.found=Impossible de trouver le r\u00e9pertoire d\u2019importation {0}.
jsexception.import.module.not.found=Impossible de trouver le module d\u2019importation {0}.
jsexception.import.multiple.values.for.single.parameter=Plusieurs valeurs ont \u00e9t\u00e9 d\u00e9tect\u00e9es pour le param\u00e8tre {0} du rapport {1}, qui ne peut en comporter qu\u2019une.
jsexception.input.stream.exhausted=Le flux d\u2019entr\u00e9e \u00e9tait satur\u00e9 avant la lecture de {0} octets.
jsexception.invalid.bean.datasource=La source de donn\u00e9es Bean {0} n\u2019est pas valide.
jsexception.invalid.class.attribute.for.model.tag=L\u2019attribut de classe du la balise mod\u00e8le, ressource {0}, n\u2019est pas valide.
jsexception.invalid.jdbc.datasource=La source de donn\u00e9es JDBC {0} n\u2019est pas valide.
jsexception.invalid.aws.datasource=La source de donn\u00e9es AWS {0} n\u2019est pas valide.
jsexception.invalid.jndi.jdbc.datasource=La source de donn\u00e9es JNDI JDBC {0} n\u2019est pas valide.
jsexception.invalid.olap.datasource=La source de donn\u00e9es OLAP {0} n\u2019est pas valide.
jsexception.invalid.resource.reference.source=La source de r\u00e9f\u00e9rence de la ressource {0} n\u2019est pas valide.
jsexception.invalid.session=La session actuelle n\u2019est pas valide. V\u00e9rifier que le serveur fonctionne et vous connecter \u00e0 nouveau.
jsexception.invalid.uri=L''URI {0} n''est pas valide.

jsexception.jar.entry.not.found=Impossible de trouver une entr\u00e9e JAR pour l\u2019URL {0}.
jsexception.jar.malformed.url=Syntaxe JAR incorrecte pour l\u2019URL {0}.
jsexception.jasperprint.not.found=Impossible de trouver l\u2019objet JasperPrint {0}.

jsexception.job.has.more.than.one.trigger=Le travail {0} poss\u00e8de plusieurs d\u00e9clencheurs.
jsexception.job.no.versions.match=La version client {0} n\u2019est pas la derni\u00e8re version ({1}).
jsexception.job.unknown.calendar.trigger.days.type=Type de jours du d\u00e9clencheur de calendrier inconnu {0}.
jsexception.job.unknown.interval.unit=Unit\u00e9 d\u2019intervalle de travail de rapport inconnue {0}.
jsexception.job.unknown.start.type=Type de d\u00e9marrage du travail de rapport inconnu {0}.
jsexception.job.unknown.trigger.bean.class=Classe Bean du d\u00e9clencheur de travail du rapport inconnue {0}.
jsexception.job.unknown.trigger.type=Type de d\u00e9clencheur du travail de rapport {0} inconnu.

jsexception.missing.olap.connection=Connexion\u00a0OLAP manquante.
jsexception.missing.olap.connection.reference=R\u00e9f\u00e9rence de connexion\u00a0OLAP manquante.
jsexception.mondrian.jdbc.datasource.has.an.invalid.type=Le type {0} de la source de donn\u00e9es JDBC de la connexion Mondrian n\u2019est pas valide.

jsexception.no.connection.selected=Aucune connexion n\u2019a \u00e9t\u00e9 s\u00e9lectionn\u00e9e.
jsexception.no.export.folder.specified=Aucun dossier d\u2019exportation n\u2019a \u00e9t\u00e9 sp\u00e9cifi\u00e9.
jsexception.no.export.zip.file.specified=Aucun fichier\u00a0ZIP d\u2019exportation n\u2019a \u00e9t\u00e9 sp\u00e9cifi\u00e9.
jsexception.no.import.folder.specified=Aucun dossier d\u2019importation n\u2019a \u00e9t\u00e9 indiqu\u00e9.
jsexception.no.import.zip.file.specified=Aucun fichier\u00a0ZIP d\u2019importation n\u2019a \u00e9t\u00e9 indiqu\u00e9.
jsexception.no.input.parameter.specified=Aucun param\u00e8tre d\u2019entr\u00e9e n\u2019a \u00e9t\u00e9 d\u00e9fini.
jsexception.no.olap.client.connection=Aucune connexion au client OLAP n\u2019a \u00e9t\u00e9 trouv\u00e9e.
jsexception.no.secure.olap.client.connection=Aucune connexion au client OLAP s\u00e9curis\u00e9e n\u2019a \u00e9t\u00e9 trouv\u00e9e.
jsexception.no.olap.model.created.for=Aucun mod\u00e8le OLAP n\u2019a \u00e9t\u00e9 cr\u00e9\u00e9 pour {0}.
jsexception.no.olap.model.name=Aucun mod\u00e8le OLAP n\u2019a \u00e9t\u00e9 sp\u00e9cifi\u00e9.
jsexception.no.olap.model.retrieved=Aucun mod\u00e8le\u00a0OLAP n\u2019a pu \u00eatre r\u00e9cup\u00e9r\u00e9.
jsexception.no.output.parameter.specified=Aucun param\u00e8tre de sortie n\u2019a \u00e9t\u00e9 sp\u00e9cifi\u00e9.
jsexception.no.persistent.class.mapped.to=Aucune classe persistante ne correspond \u00e0 {0}.
jsexception.no.resource.data.provider.found=Aucun fournisseur de donn\u00e9es de ressource n\u2019a \u00e9t\u00e9 trouv\u00e9 pour ID {0}.
jsexception.no.such.object.permission=L\u2019autorisation d\u2019objet sp\u00e9cifi\u00e9e n\u2019existe pas.
jsexception.no.such.role=Il n\u2019existe aucun r\u00f4le {0}.
jsexception.no.such.user=Il n\u2019existe aucun utilisateur {0}.
jsexception.no.uri.or.recipient.given=Aucun URI ou destinataire n\u2019a \u00e9t\u00e9 sp\u00e9cifi\u00e9.
jsexception.no.values.to.enumerate=Aucune valeur n\u2019a \u00e9t\u00e9 sp\u00e9cifi\u00e9e pour l\u2019\u00e9num\u00e9ration.
jsexception.no.values.to.enumerate={0} n\u2019est pas une URI de ressource valide.
jsexception.null.uri=URI nulle.

jsexception.output.stream.already.closed=Le flux de sortie est d\u00e9j\u00e0 ferm\u00e9.

jsexception.property.not.a.list=La propri\u00e9t\u00e9 {0} de Bean {1} n\u2019est pas une propri\u00e9t\u00e9 de la liste.
jsexception.property.not.a.map=La propri\u00e9t\u00e9 {0} de Bean {1} n\u2019est une propri\u00e9t\u00e9 de la carte.
jsexception.property.not.a.text=La propri\u00e9t\u00e9 {0} de Bean {1} n\u2019est pas une propri\u00e9t\u00e9 du texte.

jsexception.query.datasource.has.an.invalid.type=Le type de la source de donn\u00e9es de la requ\u00eate n\u2019est pas valide ({0}).

jsexception.report.job.not.found=Aucun travail de rapport portant l\u2019ID {0} n\u2019a \u00e9t\u00e9 trouv\u00e9.
jsexception.report.resource.already.exists.no.overwrite=La ressource de sortie {0} existe d\u00e9j\u00e0 et la balise de remplacement de travail n\u2019est pas d\u00e9finie.
jsexception.report.no.content.resource=La ressource {0} n\u2019est pas une ressource de contenu.
jsexception.report.unit.datasource.has.an.invalid.type=Le type de la source de donn\u00e9es de l\u2019unit\u00e9 de rapport n\u2019est pas valide ({0}).
jsexception.report.unknown.output.format=Le format de sortie du rapport {0} est inconnu.
jsexception.repository.uri.neither.report.nor.folder=L\u2019URI du r\u00e9f\u00e9rentiel {0} ne correspond ni \u00e0 une unit\u00e9 de rapport, ni \u00e0 un dossier.
jsexception.resource.already.exists=La ressource {0} existe d\u00e9j\u00e0. Entrer un autre nom.
jsexception.resource.copyTo.not.implemented=La ressource copyTo n\u2019a pas \u00e9t\u00e9 impl\u00e9ment\u00e9e.
jsexception.resource.copyFrom.not.implemented=La ressource copyFrom n\u2019a pas \u00e9t\u00e9 impl\u00e9ment\u00e9e.
jsexception.resource.does.not.exist=La ressource {0} n\u2019existe pas.
jsexception.resource.no.match.versions={0}: la version client ({1}) ne correspond pas \u00e0 la version du r\u00e9f\u00e9rentiel ({2}).
jsexception.resource.of.type.not.found=La ressource {0} de type {1} est introuvable.
jsexception.resource.not.report.unit=La ressource {0} n\u2019est pas une unit\u00e9 de rapport.
jsexception.resourcelookup.not.a.resource=ResourceLookup n\u2019est pas une ressource\u00a0: {0}.
jsexception.folder.delete.root=impossible de supprimer le dossier racine.
jsexception.report.template.not.found=L''URI de r\u00e9f\u00e9rentiel {0} n''est pas un mod\u00e8le.
jsexception.report.template.uri.not.specified=L\u2019URI de mod\u00e8le n\u2019est pas sp\u00e9cifi\u00e9.

jsexception.selected.report.not.adhoc=Le rapport s\u00e9lectionn\u00e9 n\u2019est pas un rapport \u00e0 la demande. Les unit\u00e9s de rapport standard ne sont pas prises en charge.
jsexception.session.timeout.occurred=La session\u00a0OLAP a expir\u00e9.

jsexception.too.many.data.rows=\u00c9chec de l\u2019exportation Excel en raison d\u2019un trop grand nombre de lignes de donn\u00e9es. Modifier les param\u00e8tres d\u2019exportation pour afficher une seule page par feuille.

jsexception.unable.to.complete.request=Le syst\u00e8me n\u2019a pas pu terminer votre requ\u00eate. Votre conversation s\u2019est peut-\u00eatre termin\u00e9e, a expir\u00e9 ou a \u00e9t\u00e9 rejet\u00e9e.
jsexception.undefined.file.type=Le type de fichier n\u2019est pas reconnu.
jsexception.unknown.connection.type=Le type de connexion n\u2019est pas reconnu.
jsexception.unknown.parameter.type.for.multiple.value.input=Le type de param\u00e8tre {0} n\u2019est pas valide pour l\u2019entr\u00e9e de valeurs multiple.
jsexception.unknown.permission.recipient.type=Le type de destinataire d\u2019autorisation {0} est inconnu.
jsexception.unknown.property.filter.operation=L\u2019op\u00e9ration de filtre de propri\u00e9t\u00e9 {0} est inconnue.
jsexception.unknown.timezone=Le fuseau horaire {0} est inconnu. 
jsexception.uri.not.found=L\u2019URI {0} est introuvable dans le r\u00e9f\u00e9rentiel.
jsexception.user.credentials.are.expired=Les donn\u00e9es d\u2019identification de l\u2019utilisateur {0} sont arriv\u00e9es \u00e0 expiration.
jsexception.user.disabled=La session de l\u2019utilisateur {0} est d\u00e9sactiv\u00e9e.
jsexception.user.expired=La session de l\u2019utilisateur {0} a expir\u00e9.
jsexception.user.locked=La session de l\u2019utilisateur {0} est verrouill\u00e9e.
jsexception.user.not.found=Impossible de trouver l\u2019utilisateur {0}.

jsexception.move.folder.source.uri.ancestor.destination={0} ne peut pas \u00eatre d\u00e9plac\u00e9 vers {1}. Le dossier de destination est un dossier enfant du dossier source.
jsexception.move.folder.to.same.folder=Vous ne pouvez pas d\u00e9placer le dossier {0} dans le m\u00eame dossier {1}.
jsexception.move.resource.to.same.folder=Vous ne pouvez pas d\u00e9placer la ressource {0} dans le m\u00eame dossier {1}.
jsexception.move.folder.path.already.exists=Vous ne pouvez pas d\u00e9placer le dossier {0} vers {1}. Le dossier de destination contient d\u00e9j\u00e0 un objet portant le m\u00eame nom.
jsexception.move.resource.path.already.exists=Vous ne pouvez pas d\u00e9placer la ressource {0} vers {1}. Le dossier de destination contient d\u00e9j\u00e0 un objet portant le m\u00eame nom.
jsexception.copy.resource.referenced.not.readable=Bien que la ressource {0} soit r\u00e9f\u00e9renc\u00e9e par une autre ressource, elle n\u2019est pas lisible.
jsexception.copy.resource.circular.reference=Une r\u00e9f\u00e9rence circulaire a \u00e9t\u00e9 d\u00e9tect\u00e9e pour la ressource {0}.
jsexception.folder.moved=Le dossier {0} a \u00e9t\u00e9 d\u00e9plac\u00e9 dans {1}.

report.scheduling.error.filling.report=Le rapport n\u2019a pas \u00e9t\u00e9 termin\u00e9. Une erreur s\u2019est produite pendant son ex\u00e9cution.
report.scheduling.error.exporting.report=L\u2019exportation vers {0} n\u2019a pas \u00e9t\u00e9 termin\u00e9e. Une erreur a interrompu le processus.
report.scheduling.error.saving.to.repository={0} n\u2019a pas \u00e9t\u00e9 enregistr\u00e9 dans le r\u00e9f\u00e9rentiel. Une erreur a interrompu le processus.
report.scheduling.error.sending.email.notification=La notification de t\u00e2che erron\u00e9e n\u2019a pas \u00e9t\u00e9 termin\u00e9e. Une erreur s\u2019est produite pendant son envoi.
report.scheduling.error.system=Le travail n\u2019a pas \u00e9t\u00e9 termin\u00e9. Une erreur syst\u00e8me s\u2019est produite pendant son ex\u00e9cution.

exception.report.unrecognized.number.type=Type num\u00e9rique {0} non reconnu.
exception.report.unrecognized.date.type=Type date/heure {0} non reconnu.
exception.report.unsupported.date.input.value=Vous ne pouvez pas convertir la valeur d\u2019entr\u00e9e {0} de type {1} en param\u00e8tre date/heure.
exception.report.unsupported.date.parameter.type=Type date/heure {0} non pris en charge.
exception.report.unsupported.input.control.data.type=Le type de donn\u00e9es de contr\u00f4le d''entr\u00e9e {0} n''est pas pris en charge.

jsexception.view.report.could.not.load=Impossible de trouver ou de charger l\u2019unit\u00e9 de rapport.
jsexception.view.page.does.not.exist=Page {0} introuvable dans le rapport.
jsexception.view.report.error=Une erreur s'est produite lors de la g\u00e9n\u00e9ration du rapport.
jsexception.export.unknown.argument=L\u2019option {0} est inconnue.

jsexception.mondrian.no.connection.for.resource=Il n\u2019existe aucune connexion Mondrian pour la ressource {0}.

jsexception.target.org.not.found=L\u2019organisation cible {0} est introuvable dans le r\u00e9f\u00e9rentiel.
jsexception.template.folder.not.found=Le dossier de mod\u00e8le est introuvable dans le r\u00e9f\u00e9rentiel.

jsexception.search.duplicate.label=Un objet portant le libell\u00e9 {0} existent d\u00e9j\u00e0 dans le dossier {1}.
jsexception.search.duplicate.name=Un objet portant le nom {0} existent d\u00e9j\u00e0 dans le dossier {1}.

report.scheduling.error.saving.data.snapshot.disabled=L'enregistrement des instantan\u00e9s de donn\u00e9es est d\u00e9sactiv\u00e9.
report.scheduling.error.data.snapshot.not.populated=Impossible de remplir l'instantan\u00e9 de donn\u00e9es.
report.scheduling.error.data.snapshot.not.persistable=Impossible d'enregistrer l'instantan\u00e9 de donn\u00e9es.
report.scheduling.error.saving.data.snapshot.failed=Erreur lors de l'enregistrement de l'instantan\u00e9 de donn\u00e9es.

exception.remote.resource.already.exists=La ressource {0} existe d\u00e9j\u00e0.
exception.remote.resource.not.found=Ressource {0} introuvable.
exception.remote.resource.type.not.supported=La ressource de type {0} n\u2019est pas prise en charge par cette op\u00e9ration.
exception.remote.folder.not.found=Dossier {0} introuvable ou n\u2019est pas un dossier.
exception.remote.unexpected.error=Erreur inattendue.
exception.remote.weak.password=Mot de passe faible.
exception.remote.resource.not.ready=La t\u00e2che {0} n''est pas encore termin\u00e9e.
exception.remote.no.such.export.process=Aucune t\u00e2che dexportation ne poss\u00e8de lidentifiant {0}.
exception.remote.no.such.import.process=Aucune t\u00e2che d''importation ne poss\u00e8de l''identifiant {0}.
exception.remote.access.denied=Acc\u00e8s refus\u00e9.
exception.remote.modification.not.allowed=Une modification de la ressource {0} n\u2019est pas autoris\u00e9e.
exception.remote.illegal.parameter.value.error=La valeur "{1}" du param\u00e8tre "{0}" n\u2019est pas valide.
exception.remote.mandatory.parameter.error=Le param\u00e8tre obligatoire ''{0}'' est manquant.
exception.remote.import.failed=Echec de l''importation. Raison: {0}
exception.remote.import.failed.zip.error=Echec de l'importation. Raison : Impossible de lire le fichier compress\u00e9.
exception.remote.import.failed.content.error=\u00c9chec de l\u2019importation. Raison : le fichier zip fourni n\u2019est pas un fichier d\u2019exportation JasperReports Server valide.
exception.remote.resource.querying.not.supported=La ressource {0} ne prend en charge l\u2019interrogation
exception.remote.version.not.match=Echec de la mise \u00e0 jour : les versions ne correspondent pas.

#AWS data source specific exception messages
aws.exception.datasource.recovery.base=Une exception s\u2019est produite lors de la r\u00e9cup\u00e9ration de la source de donn\u00e9es AWS : {0}.
aws.exception.datasource.recovery.timeout=Il peut s\u2019agir d\u2019un probl\u00e8me li\u00e9 \u00e0 l\u2019URL JDBC, aux param\u00e8tres de s\u00e9curit\u00e9 AWS ou au processus de r\u00e9cup\u00e9ration de la source de donn\u00e9es AWS, qui peut prendre jusqu\u2019\u00e0 2 minutes.
aws.exception.datasource.recovery.instance.not.active=L\u2019instance de la source de donn\u00e9es AWS n\u2019est pas active.
aws.exception.datasource.recovery.is.not.possible=La source de donn\u00e9es AWS ne peut pas \u00eatre r\u00e9cup\u00e9r\u00e9e automatiquement car votre JasperReports Server et instance de base de donn\u00e9es ne se trouvent pas dans le m\u00eame VPC.
aws.exception.datasource.recovery.public.ip.not.provided=Vous devez indiquer l\u2019adresse IP publique d\u2019entr\u00e9e de ce serveur dans les param\u00e8tres AWS pour pouvoir utiliser la configuration et la r\u00e9cup\u00e9ration automatis\u00e9es de la source de donn\u00e9es AWS.
aws.exception.datasource.recovery.public.ip.not.determined=Impossible de d\u00e9terminer l\u2019adresse IP d\u2019instance pour la r\u00e9cup\u00e9ration de la source de donn\u00e9es AWS.
aws.exception.datasource.load.default.credentials=Cette instance ne peut pas utiliser les <b>informations d'identification d'instance EC2</b> pour se connecter automatiquement \u00e0 Amazon RDS et Amazon Redshift, car aucun r\u00f4le de gestion des identit\u00e9s et des acc\u00e8s (IAM) n'y a \u00e9t\u00e9 affect\u00e9. Pour d\u00e9couvrir comment lancer un serveur capable de se connecter automatiquement aux sources de donn\u00e9es AWS en toute s\u00e9curit\u00e9, veuillez lire la section <a class='launcher inline' href='http://community.jaspersoft.com/jaspersoft-aws/launch' target='_blank'>Lancement de Jaspersoft pour AWS</a> t<br><br>Sinon, vous pouvez utiliser les <b>informations d'identification AWS</b>.
aws.exception.datasource.rds.vpc.recovery=Impossible d\u2019attribuer automatiquement le groupe de s\u00e9curit\u00e9 VPC nomm\u00e9 {0} \u00e0 l\u2019instance RDS {1}. L\u2019op\u00e9ration n\u2019est actuellement pas prise en charge par l\u2019API AWS. Attribuez manuellement le groupe de s\u00e9curit\u00e9 \u00e0 votre instance RDS.
aws.exception.datasource.accessKey.invalid=La cl\u00e9 d\u2019acc\u00e8s AWS n\u2019est pas valide.
aws.exception.datasource.secretKey.invalid=La cl\u00e9 secr\u00e8te AWS n\u2019est pas valide.

#Cluster specific exception messages
cluster.exception.session.attribute.missing=Une erreur non li\u00e9e s'est produite sur le serveur. Votre session a \u00e9t\u00e9 red\u00e9marr\u00e9e, mais tout travail non enregistr\u00e9 sera perdu. Veuillez nous excuser pour la g\u00eane occasionn\u00e9e.<p><p>Cliquez sur le lien <a class="launcher inline" href="home.html">Aller \u00e0 la page d'accueil</a> pour revenir \u00e0 la page d'accueil et recommencer. Si vous rencontrez une autre erreur, veuillez contacter votre administrateur.
cluster.exception.session.attribute.missing.popup=Une erreur non li\u00e9e s'est produite sur le serveur. Votre session a \u00e9t\u00e9 red\u00e9marr\u00e9e, mais tout travail non enregistr\u00e9 sera perdu. Veuillez nous excuser pour la g\u00eane occasionn\u00e9e.<p><p>Cliquez sur le lien ci-dessous pour revenir \u00e0 la page d'accueil et recommencer. Si vous rencontrez une autre erreur, veuillez contacter votre administrateur.