#
# Copyright (C) 2005 - 2019 TIBCO Software Inc. All rights reserved.
# http://www.jaspersoft.com.
#
# Unless you have purchased a commercial license agreement from Jaspersoft,
# the following license terms apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

jsexception.access.denied=You do not have permission to take the requested action. Log in as a permitted user if you can.
jsexception.any={0}

jsexception.bean.has.no.method=The bean with the name {0} does not have method {1}.
jsexception.bean.name.not.found.for.interface=No bean name was found for interface {0}.
jsexception.bean.no.name=A bean with the name {0} cannot be found.
jsexception.bean.not.a.ReportDataSourceService=The {0} bean is not a ReportDataSourceService.

jsexception.call.not.supported=The call is not supported by resource lookup objects.
jsexception.connection.type.not.suported=The connection type is not supported.
jsexception.connection.uri.not.specified=The connection URI is not specified.
jsexception.could.not.find.resource.with.uri=The resource with URI {0} cannot be found. 
jsexception.could.not.find.content.resource.with.uri=The content resource with URI {0} cannot be found.
jsexception.unexpected.resource.type.at.uri=Unexpected type ({0}) of the resource with URI {1} 

jsexception.default.message=An unexplained error occurred. Please contact your system administrator.

jsexception.error.creating.connection=An error occurred while creating the connection. Try again.
jsexception.parameter.has.multiple.values=Parameter {0} has multiple values.

jsexception.parameter.has.no.value=Parameter {0} has no value.


jsexception.failed.to.create.connection=The connection could not be made.
jsexception.failed.to.save.connection=The connection was not saved.
jsexception.failed.to.save.connection.changes=The connection changes were not saved.
jsexception.file.resource.is.reference=File resource {0} is a reference and has no data.
jsexception.file.resource.no.match.type=The declared type of resource ({0}) does not match the actual type of the reference ({1}).
jsexception.folder.already.exists=A folder with the name {0} already exists. Choose a different name.
jsexception.folder.details.not.found=Folder details for folder {0} were not found in the import information. 
jsexception.folder.not.found=The folder {0} cannot be found. 
jsexception.folder.not.found.at=The folder is not at {0}.
jsexception.folder.duplicate.name=There is already a folder named {0} in {1}.
jsexception.folder.duplicate.label=Duplicate folder label {0} in folder {1}.
jsexception.folder.too.long.uri=The URI of the folder is too long. The maximum length is {0} characters.
jsexception.folder.creation.not.allowed={0} is a reserved name and not allowed in {1}.

jsexception.got.null.schema.source.wrapper=The subflow returned a null schema source wrapper.
jsexception.got.null.access.grant.source.wrapper=The subflow returned a null access grant source wrapper.
jsexception.got.null.connection.back=The subflow returned a null connection.

jsexception.implementation.class.does.not.implement=Implementation class {0} does not implement {1}.
jsexception.implementation.class.not.found=An implementation class for {0} cannot be found.
jsexception.import.directory.not.found=The import directory {0} cannot be found.
jsexception.import.module.not.found=The import module {0} cannot be found.
jsexception.import.multiple.values.for.single.parameter=Multiple parameter values were found for the single-value parameter {0} of report {1}.
jsexception.input.stream.exhausted=The input stream was exhausted before reading {0} bytes.
jsexception.invalid.bean.datasource=The bean data source {0} is invalid.
jsexception.invalid.class.attribute.for.model.tag=The class attribute for model tag, resource {0}, is invalid.
jsexception.invalid.jdbc.datasource=The JDBC data source {0} is invalid.
jsexception.invalid.aws.datasource=The AWS data source {0} is invalid.
jsexception.invalid.azureSql.datasource=The Azure SQL data source {0} is invalid.
jsexception.invalid.jndi.jdbc.datasource=The JNDI JDBC data source {0} is invalid.
jsexception.invalid.olap.datasource=The OLAP data source {0} is invalid.
jsexception.invalid.resource.reference.source=The resource reference source {0} is invalid.
jsexception.invalid.session=The current session is invalid. Make sure the server is running and try logging in again.
jsexception.invalid.uri=The URI {0} is invalid.

jsexception.jar.entry.not.found=A JAR entry for URL {0} cannot be found.
jsexception.jar.malformed.url=The JAR URL {0} has incorrect syntax.
jsexception.jasperprint.not.found=The JasperPrint object {0} cannot be found.

jsexception.job.has.more.than.one.trigger=Job {0} has more than one trigger.
jsexception.job.no.versions.match=Client version {0} is not the latest version ({1}).
jsexception.job.unknown.calendar.trigger.days.type=Unknown calendar trigger days type {0}.
jsexception.job.unknown.interval.unit=Unknown report job interval unit {0}.
jsexception.job.unknown.start.type=Unknown report job start type {0}.
jsexception.job.unknown.trigger.bean.class=Unknown report job trigger bean class {0}.
jsexception.job.unknown.trigger.type=Unknown report job trigger type {0}.

jsexception.missing.olap.connection=The OLAP connection is missing.
jsexception.missing.olap.connection.reference=The OLAP connection reference is missing.
jsexception.mondrian.jdbc.datasource.has.an.invalid.type=The Mondrian connection JDBC data source is an invalid type ({0}).

jsexception.no.connection.selected=No connection is selected.
jsexception.no.export.folder.specified=No export folder was specified.
jsexception.no.export.zip.file.specified=No export ZIP file was specified.
jsexception.no.import.folder.specified=No import folder was specified.
jsexception.no.import.zip.file.specified=No import ZIP file was specified.
jsexception.no.input.parameter.specified=No input parameter was specified.
jsexception.no.olap.client.connection=No OLAP client connection can be found.
jsexception.no.secure.olap.client.connection=No Secure OLAP client connection can be found.
jsexception.no.olap.model.created.for=No OLAP Model was created for {0}.
jsexception.no.olap.model.name=No OLAP Model was specified.
jsexception.no.olap.model.retrieved=No OLAP Model could be retrieved.
jsexception.no.output.parameter.specified=No output parameter was specified.
jsexception.no.persistent.class.mapped.to=No persistent class is mapped to {0}.
jsexception.no.resource.data.provider.found=No resource data provider was found for ID {0}.
jsexception.no.such.object.permission=The specified object permission does not exist.
jsexception.no.such.role=There is no role {0}.
jsexception.no.such.user=There is no user {0}.
jsexception.no.uri.or.recipient.given=No URI or recipient was specified.
jsexception.no.values.to.enumerate=No values were specified to enumerate.
jsexception.no.values.to.enumerate={0} is not a valid resource URI.
jsexception.null.uri=Null URI.

jsexception.output.stream.already.closed=The output stream is already closed.

jsexception.property.not.a.list=Property {0} of bean {1} is not a list property.
jsexception.property.not.a.map=Property {0} of bean {1} is not a map property.
jsexception.property.not.a.text=Property {0} of bean {1} is not a text property.

jsexception.query.datasource.has.an.invalid.type=The query data source has an invalid type ({0}).

jsexception.report.job.not.found=A report job with ID {0} cannot be found.
jsexception.report.resource.already.exists.no.overwrite=Output resource {0} already exists and the job overwrite flag is not set.
jsexception.report.no.content.resource=Resource {0} is not a content resource.
jsexception.report.unit.datasource.has.an.invalid.type=The report unit data source has an invalid type ({0}).
jsexception.report.unknown.output.format=Report output format {0} is not a known format.
jsexception.repository.uri.neither.report.nor.folder=The repository URI {0} is neither a report unit nor a folder.
jsexception.resource.already.exists=Resource {0} already exists. Choose a different name.
jsexception.resource.copyTo.not.implemented=Resource copyTo is not implemented.
jsexception.resource.copyFrom.not.implemented=Resource copyFrom is not implemented.
jsexception.resource.does.not.exist=Resource {0} does not exist.
jsexception.resource.no.match.versions={0}: client version {1} does not match the repository version ({2}).
jsexception.resource.of.type.not.found=Resource {0} of type {1} cannot be found.
jsexception.resource.not.report.unit=Resource {0} is not a report unit.
jsexception.resourcelookup.not.a.resource=ResourceLookup is not a resource: {0}.
jsexception.folder.delete.root=The root folder cannot be deleted.
jsexception.report.template.not.found=The repository URI {0} is not a report template.
jsexception.report.template.uri.not.specified=The template URI is not specified.

jsexception.selected.report.not.adhoc=The selected report is not an Ad Hoc report. Regular report units are not supported.
jsexception.session.timeout.occurred=The OLAP session timed out.

jsexception.too.many.data.rows=The Excel exporter failed because of too many data rows. You can change your exporter settings to one page per sheet.

jsexception.unable.to.complete.request=The system was unable to complete you request. Your conversation may have ended, expired, or been invalidated.
jsexception.undefined.file.type=The file type  is not recognized.
jsexception.unknown.connection.type=The connection type is not recognized.
jsexception.unknown.parameter.type.for.multiple.value.input=The parameter type {0} is not valid for multiple value input.
jsexception.unknown.permission.recipient.type=Permission recipient type {0} is not recognized.
jsexception.unknown.property.filter.operation=Property filter operation {0} is not recognized.
jsexception.unknown.timezone=The time zone {0} is not recognized. 
jsexception.uri.not.found=URI {0} cannot be found in the repository.
jsexception.user.credentials.are.expired=User {0}'s credentials have expired.
jsexception.user.disabled=User {0} is disabled.
jsexception.user.expired=User {0} has expired.
jsexception.user.locked=User {0} is locked.
jsexception.user.not.found=User {0} cannot be found.

jsexception.move.folder.source.uri.ancestor.destination={0} cannot be moved to {1}. The destination is a child of the source.
jsexception.move.folder.to.same.folder=You cannot move folder {0} to the same folder {1}.
jsexception.move.resource.to.same.folder=You cannot move resource {0} to the same folder {1}.
jsexception.move.folder.path.already.exists=You cannot move folder {0} to {1}. The destination folder already contains an object with the same name.
jsexception.move.resource.path.already.exists=You cannot move resource {0} to {1}. The destination already contains an object with the same name.
jsexception.copy.resource.referenced.not.readable=Resource {0} is referenced by another resource but it is not readable.
jsexception.copy.resource.circular.reference=A circular reference was detected for resource {0}.
jsexception.folder.moved=Folder {0} has moved to {1}.

report.scheduling.error.filling.report=The report was not completed. An error occurred while executing it.
report.scheduling.error.exporting.report=The export to {0} was not completed. An error interrupted the process.
report.scheduling.error.saving.to.repository={0} was not saved to the repository. An error interrupted the process.
report.scheduling.error.sending.email.notification=The job error notification was not completed. An error occurred while sending it.
report.scheduling.error.system=The job was not completed. A system error occurred while running it.

exception.report.unrecognized.number.type=Unrecognized numeric type {0}
exception.report.unrecognized.date.type=Unrecognized date/time type {0}
exception.report.unsupported.date.input.value=You cannot convert input value {0} of type {1} to a date/time parameter.
exception.report.unsupported.date.parameter.type=Unsupported date/time type {0}
exception.report.unsupported.input.control.data.type=Input control data type {0} is not supported.

jsexception.view.report.could.not.load=The report unit cannot be found or it cannot be loaded.
jsexception.view.page.does.not.exist=Page {0} not found in report
jsexception.view.report.error=An error occurred during report generation
jsexception.export.unknown.argument=Option {0} is not recognized.

jsexception.mondrian.no.connection.for.resource=There is no Mondrian connection for resource {0}.

jsexception.target.org.not.found=Target organization {0} cannot be found in the repository.
jsexception.template.folder.not.found=The template folder cannot be found in the repository.

jsexception.search.duplicate.label=An object with the label {0} already exists in folder {1}.
jsexception.search.duplicate.name=An object with the name {0} already exists in folder {1}.

report.scheduling.error.saving.data.snapshot.disabled=Saving data snapshots is disabled.
report.scheduling.error.data.snapshot.not.populated=Data snapshot was not populated.
report.scheduling.error.data.snapshot.not.persistable=Data snapshot cannot be saved.
report.scheduling.error.saving.data.snapshot.failed=Error while saving data snapshot.

exception.remote.resource.already.exists=Resource {0} already exists.
exception.remote.resource.not.found=Resource {0} not found.
exception.remote.resource.type.not.supported=Resource {0} type is not supported by this operation.
exception.remote.folder.not.found=Folder {0} not found or it is not a folder.
exception.remote.unexpected.error=Unexpected error.
exception.remote.weak.password=Weak password.
exception.remote.attribute.permission.order.invalid=The attribute permission for {0} can't be modified to a stronger permission {1}. \
   Choose a permission that is more restrictive or equal to the inherited permission {2}.
exception.remote.attribute.permission.recipient.invalid=The attribute permission recipient {0} for {1} is invalid.
exception.remote.resource.not.ready=Task {0} not finished yet.
exception.remote.no.such.export.process=No export task with id {0}.
exception.remote.no.such.import.process=No import task with id {0}.
exception.remote.access.denied=Access denied.
exception.remote.modification.not.allowed=Modification of the resource {0} is not allowed.
exception.remote.illegal.parameter.value.error=The value "{1}" for parameter "{0}" is invalid.

exception.remote.query.reference.integrity.error=Query has broken or inappropriate references to query fields.
exception.remote.query.filter.reference.class.error=Filter references field {0} with unsupported type {1}
exception.remote.query.order.generic.reference.class.error=Order statement references field {0} of unsupported type {1}
exception.remote.query.order.header.null.reference.error=Header order statement has no reference to query level
exception.remote.query.order.header.reference.class.error=Header order statement references field {0} of unsupported type {1}
exception.remote.query.expansion.header.null.reference.error=Header expansion statement has no reference to query level
exception.remote.query.expansion.level.reference.class.error=Header expansion statement references field {0} of unsupported type {1}
exception.remote.query.expansion.level.ambiguous.reference.error=Header expansion references not uniquely identifiable field {0}
exception.remote.query.aggregated.field.reference.class.error=Header expansion statement references field {0} of unsupported type {1}

exception.remote.mandatory.parameter.error=The mandatory parameter "{0}" is missing.
exception.remote.mandatory.olap.parameter.select.aggregations.error=The mandatory parameter "select.aggregations" is missing.
exception.remote.mandatory.olap.parameter.groupBy.columns.error=The mandatory parameter "groupBy.columns" is missing.
exception.remote.mandatory.olap.parameter.groupBy.aggregations.error=The mandatory parameter "aggregations" for "groupBy.columns" or "groupBy.rows" is missing.
exception.remote.parameter.groupBy.multiple.aggregations.error=Multiple "aggregations" parameters were found. Only one parameter is allowed for "groupBy.columns" or "groupBy.rows"
exception.remote.import.failed=Import failed. Reason: {0}
exception.remote.import.failed.zip.error=Import failed. Reason: cannot read zip file.
exception.remote.import.failed.content.error=Import failed. Reason: provided zip file is not valid JasperReports Server export file.
exception.remote.resource.querying.not.supported=Resource {0} doesn't support querying
exception.remote.version.not.match=Update failed: versions not match
exception.remote.query.where.parameters.name.is.not.valid=A parameter name in the WHERE clause is not valid. Names must start with a letter and contain only alphanumeric characters (A-Za-z0-9) and _ (underscore).
exception.remote.serialization.error= Serialization error.

exception.remote.query.level.hierarchy.not.valid=Levels from one dimension have different hierarchy. Only levels from a single hierarchy can be selected.
exception.remote.olap.query.limit.not.supported=Query limit is not supported for OLAP.
exception.remote.query.calculated.field.expression.missing=Missing calculated field expression.
exception.remote.path.list.not.valid=Path segment contains invalid characters.
exception.remote.query.calculated.field.expression.not.valid=Query calculated field expression is not valid.
exception.remote.timezone.is.not.valid=The timezone {0} is not valid.

#AWS data source specific exception messages
aws.exception.datasource.recovery.base=Exception occurred during AWS data source recovery: {0}.
aws.exception.datasource.recovery.timeout=There may be a problem with the JDBC URL, AWS Security Settings or the AWS Data Source recovery process, which can take up to 2 minutes.
aws.exception.datasource.recovery.instance.not.active=The AWS data source instance is not active.
aws.exception.datasource.recovery.is.not.possible=The AWS data source can not be recovered automatically, because your JasperReports Server and database instance are not located in the same VPC.
aws.exception.datasource.recovery.public.ip.not.provided=You must provide the 'Ingress Public IP' of this server in Cloud Settings to use automated AWS Data Source setup and recovery.
aws.exception.datasource.recovery.public.ip.not.determined=Unable to determine instance IP address for AWS Data Source recovery.
aws.exception.datasource.load.default.credentials=This instance cannot use <b>EC2 instance credentials</b> to connect automatically to Amazon RDS and Amazon Redshift, because it does not have an Identity and Access Management (IAM) Role assigned. Please read <a class='launcher inline' href='http://community.jaspersoft.com/jaspersoft-aws/launch' target='_blank'>Launching Jaspersoft for AWS</a> to learn how to launch a server which is able to automatically connect to AWS data sources securely.<br><br>As a workaround you can use <b>AWS credentials</b>.
aws.exception.datasource.rds.vpc.recovery=Unable to automatically assign the VPC security group named {0} to RDS instance {1}. The operation is not currently supported by the AWS API. Please manually assign the security group to your RDS instance.
aws.exception.datasource.accessKey.invalid=AWS Access Key is invalid.
aws.exception.datasource.secretKey.invalid=AWS Secret Key is invalid.

#AZURE data source specific exception messages
azure.exception.datasource.recovery.public.ip.not.provided=You must provide the 'Ingress Public IP' of this server in Cloud Settings to use automated Azure Data Source setup and recovery.
azure.exception.datasource.recovery.firewall.rule.name.not.provided=You must provide the 'Firewall Rule Name' of this server in Cloud Settings to use automated Azure Data Source setup and recovery.
azure.exception.datasource.recovery.server.name.not.provided=You must provide the 'Server Name' of this server to use automated Azure Data Source setup and recovery.
azure.exception.datasource.recovery.subscription.id.not.provided=You must provide the 'Subscription ID' to use automated Azure Data Source setup and recovery.
azure.exception.datasource.recovery.key.store.file.not.provided=You must provide the 'Key Store File' to use automated Azure Data Source setup and recovery.
azure.exception.datasource.recovery.key.store.type.not.provided=You must provide the 'Key Store Type' to use automated Azure Data Source setup and recovery.
azure.exception.datasource.key.error=Error reading certificate file from repository. Verify that the certificate file and password are valid.
azure.exception.datasource.auth.error=Authentication error. Verify that the subscription id and certificate are valid.
azure.exception.datasource.cannot.retrieve.database.list=Unable to retrieve databases from sql management.
azure.exception.datasource.cannot.ensure.firewall.rule=Unable to ensure Azure firewall rule.
azure.exception.datasource.cannot.recover.datasource=Unable to recover Azure Data Source.

#Cluster specific exception messages
cluster.exception.session.attribute.missing=An unrelated error has occurred on the server. Your session was restarted, but any unsaved work has been lost. Please excuse the inconvenience.<p><p>Click the following link to go back to the home page and start again: <a class="launcher inline" href="home.html">Go to home page</a>. If you encounter another error, please contact your administrator.
cluster.exception.session.attribute.missing.popup=An unrelated error has occurred on the server. Your session was restarted, but any unsaved work has been lost. Please excuse the inconvenience.<p><p>Click the button below to go back to the home page and start again. If you encounter another error, please contact your administrator.

#Profile attributes substitution error and debug level messages
profile.attribute.exception.substitution.base = There was an attribute substitution error in the field "{1}" of resource "{0}".
profile.attribute.substitution.not.found = The attribute name "{0}" is not defined in the "{1}".
profile.attribute.substitution.not.found.in.resource = There was an attribute substitution error in the field "{1}" of resource "{0}". The attribute name "{2}" is not defined in the "{3}".
profile.attribute.substitution.category.invalid = In attribute "{1}", the category "{0}" is not valid. It must be one of "{2}".
profile.attribute.substitution.category.invalid.in.resource = There was an attribute substitution error in the field "{1}" of resource "{0}". In attribute "{3}", the category "{2}" is not valid. It must be one of "{4}".
profile.attribute.debug.substitution.success = The attribute "{0}" substituted in resource "{1}". New "{2}" field value: "{3}".

#Query execution exceptions.
query.execution.not.found=The query execution ID "{0}" was not found on the server.
query.execution.cancelled=The query execution ID "{0}" is cancelled.
query.datasource.invalid=The data source "{0}" caused an error during query execution.
datasource.connection.failed=The data source connection failed.

#Paging exceptions.
paging.offset.out.of.range = The specified row offset is invalid. The offset must be between "{0}" and "{1}".
paging.page.size.out.of.range = The specified page size is invalid. The page size must be greater than "{0}".
query.limit.out.of.range = The specified query limit is invalid. The query limit must be between "{0}" and "{1}".
paging.axis.count.out.of.range=The paging axis count must not be greater than 1 for multi-level or 2 for multi-axis queries.

# Ad Hoc REST
query.where.parameter.not.valid=The parameter "{0}" has invalid value "{1}" for operator "{2}".
query.field.ids.collision=The query field IDs "{0}" conflict with an existing query field ID or data source field name.
query.field.ids.metadata.field.collision=The query field IDs "{0}" conflict with an existing metadata field name.
query.parameter.name.query.field.id.collision=Query parameter name "{0}" conflicts with existing query field id.
query.parameter.name.metadata.field.collision=Query parameter name "{0}" conflicts with metadata field.
report.missing.data.source.fields=The report contains one or more items that are not in the source data. You must edit the Ad Hoc View that was used to create this report, and re-save the report.
adhoc.missing.data.source.fields=The view contains one or more items that are not in the source data. You must edit the Ad Hoc View.
query.in.memory.datasource.type.not.supported=The value for "{0}" is not valid. The in-memory data source is of type "{1}", which is not supported for query execution.
expression.representation.required = In "{0}", either the expression object or an expression string must be specified, but both representations are null.
query.datasource.not.found=The data source URI "{0}" was not found on the server.
query.datasource.access.denied=You do not have permission to access the data source "{0}".
query.aggregate.definition.error=The aggregate definition cannot have both an aggregate function and an expression.
query.fields.from.multiple.dataislands=The query fields "{0}" and "{1}" are in separate data islands and cannot be queried together.
query.datasource.type.not.supported=The data source "{0}" is a type that is not supported for query execution.
query.datasource.olap.view.not.supported=The data source "{0}" is based on an OLAP View, which is not supported for query execution.
query.where.expression.type.not.supported=The query WHERE expression of type "{0}" is not supported.
query.expression.not.valid=Query expression is not valid.
query.aggregate.expression.not.valid=The aggregation expression "{1}" in aggregated field "{0}" is not a valid expression.
query.aggregation.expression.not.valid=Query aggregation expression is not valid

query.select.illegal.fields.state=Simultaneous selection of fields and distinctFields are not allowed

query.aggregation.function.name.not.valid=The aggregation function name "{1}" in aggregated field "{0}" is not a recognized function.
query.groupBy.allGroup.not.first=In the query groups "{0}", "allGroup" must be in the first position.
query.groupBy.categorizer.not.valid=The GROUP BY categorizer "{0}" does not have a valid name.
query.multiAxis.aggregation.is.empty=The aggregation array in a multi-axis query cannot be empty.
query.orderBy.topOrBottom.limit.not.valid=The ORDER BY limit "{0}" has value "{1}" but cannot be less than 1.
query.orderBy.level.reference.not.valid=The query ORDER BY level "{0}" cannot be resolved. The aggregation flag is missing or the fieldRef is not valid.

query.where.parameters.expression.not.valid=The parameter expressions in the WHERE clause are not supported or not valid.
query.where.parameters.expression.type.not.valid=The parameter "{0}" of the WHERE expression is invalid for the "{1}" operator. It must be one of the following types: "{2}"
query.details.unsupported=Multi-axis queries do not support details. The SELECT expression cannot define any fields.
query.invalid.structure=The query must contain at least one non-empty clause, either the SELECT or GROUP BY expression.
query.transformation.topn.not.allowed.aggregations.in.rows=Top N or bottom N filters aren't allowed when a multi-axis query contains aggregations in rows.
attribute.patterns.contains.invalid = List of attribute patterns contains invalid pattern {0}. It misses next named-capturing group(s): {1}

query.expression.operands.size.out.of.bound=The size of the query expressions operands "{0}" must be between "{1}" and "{2}".
query.expansion.level.reference.not.valid = The query expansion level "{0}" cannot be resolved.
query.metadata.fields.not.found = The query fields "{0}" do not exist in the data source.