#
# Copyright (C) 2005 - 2019 TIBCO Software Inc. All rights reserved.
# http://www.jaspersoft.com.
#
# Unless you have purchased a commercial license agreement from Jaspersoft,
# the following license terms apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

jsexception.access.denied=no tiene permiso para realizar la acci\u00F3n solicitada. Inicie sesi\u00F3n como usuario permitido si puede.
jsexception.any={0}

jsexception.bean.has.no.method=El bean con nombre {0} no tiene m\u00E9todo {1}.
jsexception.bean.name.not.found.for.interface=No se ha encontrado ning\u00FAn nombre de bean para la interfaz {0}.
jsexception.bean.no.name=No existe un bean con el nombre {0}.
jsexception.bean.not.a.ReportDataSourceService=El bean {0} no es un ReportDataSourceService.

jsexception.call.not.supported=Los objetos de b\u00FAsqueda de recursos no admiten la llamada.
jsexception.connection.type.not.suported=No se admite este tipo de conexi\u00F3n.
jsexception.connection.uri.not.specified=URI de conexi\u00F3n no especificado
jsexception.could.not.find.resource.with.uri=No existe el recurso con URI {0}. 
jsexception.could.not.find.content.resource.with.uri=No existe el recurso de contenido con URI {0}.
jsexception.unexpected.resource.type.at.uri=Tipo inesperado ({0}) del recurso con la URI {1} 

jsexception.default.message=Se ha producido un error desconocido. P\u00F3ngase en contacto con el administrador del sistema.

jsexception.error.creating.connection=Se ha producido un error al crear la conexi\u00F3n. Vuelva a intentarlo.
jsexception.parameter.has.multiple.values=El par\u00E1metro {0} tiene varios valores.

jsexception.parameter.has.no.value=El par\u00E1metro {0} no tiene ning\u00FAn valor.


jsexception.failed.to.create.connection=No se ha podido realizar la conexi\u00F3n.
jsexception.failed.to.save.connection=No se guard\u00F3 la conexi\u00F3n.
jsexception.failed.to.save.connection.changes=No se guardaron los cambios de la conexi\u00F3n.
jsexception.file.resource.is.reference=El recurso de archivo {0} es una referencia y no tiene datos.
jsexception.file.resource.no.match.type=El tipo declarado del recurso ({0}) no coincide con el tipo real de la referencia ({1}).
jsexception.folder.already.exists=Ya existe una carpeta con el nombre {0}. Elija un nombre diferente.
jsexception.folder.details.not.found=No se han encontrado los detalles de la carpeta {0} en la informaci\u00F3n de importaci\u00F3n. 
jsexception.folder.not.found=No existe la carpeta {0}. 
jsexception.folder.not.found.at=La carpeta no est\u00E1 en {0}.
jsexception.folder.duplicate.name=Ya existe una carpeta con nombre {0} en {1}.
jsexception.folder.duplicate.label=Etiqueta de carpeta {0} duplicada en carpeta {1}.
jsexception.folder.too.long.uri=La URI de la carpeta es demasiado larga. La longitud m\u00E1xima es de {0} caracteres.
jsexception.folder.creation.not.allowed={0} es un nombre reservado y no se permite en {1}.

jsexception.got.null.schema.source.wrapper=El subflujo devolvi\u00F3 un contenedor de origen de esquema nulo.
jsexception.got.null.access.grant.source.wrapper=El subflujo devolvi\u00F3 un contenedor de concesi\u00F3n de acceso nulo.
jsexception.got.null.connection.back=El subflujo devolvi\u00F3 una conexi\u00F3n nula.

jsexception.implementation.class.does.not.implement=La clase de implementaci\u00F3n {0} no implementa {1}.
jsexception.implementation.class.not.found=No existe una clase de implementaci\u00F3n para {0}.
jsexception.import.directory.not.found=No existe el directorio de importaci\u00F3n {0}.
jsexception.import.module.not.found=No existe el m\u00F3dulo de importaci\u00F3n {0}.
jsexception.import.multiple.values.for.single.parameter=Se han encontrado varios valores de par\u00E1metro para el par\u00E1metro de valor \u00FAnico {0} del informe {1}.
jsexception.input.stream.exhausted=Secuencia de entrada agotada antes de leer {0} bytes.
jsexception.invalid.bean.datasource=Origen de datos bean {0} no v\u00E1lido.
jsexception.invalid.class.attribute.for.model.tag=Atributo de clase no v\u00E1lido para la etiqueta de modelo, recurso {0}.
jsexception.invalid.jdbc.datasource=El origen de datos JDBC {0} no es v\u00E1lido.
jsexception.invalid.aws.datasource=El origen de datos de AWS {0} no es v\u00E1lido.
jsexception.invalid.azureSql.datasource=El origen de datos SQL de Azure {0} no es v\u00E1lido.
jsexception.invalid.jndi.jdbc.datasource=Origen de datos JDBC de JNDI {0} no v\u00E1lido.
jsexception.invalid.olap.datasource=Origen de datos OLAP {0} no v\u00E1lido.
jsexception.invalid.resource.reference.source=Origen de referencia de recurso {0} no v\u00E1lido.
jsexception.invalid.session=Sesi\u00F3n actual no v\u00E1lida. Aseg\u00FArese de que el servidor se est\u00E1 ejecutando e intente iniciar sesi\u00F3n de nuevo.
jsexception.invalid.uri=La URI {0} no es v\u00E1lida.

jsexception.jar.entry.not.found=No existe una entrada de JAR para la URL {0}.
jsexception.jar.malformed.url=La URL de JAR {0} posee una sintaxis incorrecta.
jsexception.jasperprint.not.found=No existe el objeto de JasperPrint {0}.

jsexception.job.has.more.than.one.trigger=El trabajo {0} tiene m\u00E1s de un desencadenador.
jsexception.job.no.versions.match=La versi\u00F3n {0} del cliente no es la m\u00E1s reciente ({1}).
jsexception.job.unknown.calendar.trigger.days.type=Tipo de d\u00EDas de desencadenador de calendario desconocido {0}.
jsexception.job.unknown.interval.unit=Unidad de intervalo de trabajo de informe desconocido {0}.
jsexception.job.unknown.start.type=Tipo de inicio de trabajo de informe desconocido {0}.
jsexception.job.unknown.trigger.bean.class=Clase de bean de desencadenador de trabajo de informe desconocida {0}.
jsexception.job.unknown.trigger.type=Tipo de desencadenador de trabajo de informe desconocido {0}.

jsexception.missing.olap.connection=Falta la conexi\u00F3n OLAP.
jsexception.missing.olap.connection.reference=Falta la referencia de conexi\u00F3n OLAP.
jsexception.mondrian.jdbc.datasource.has.an.invalid.type=El origen de datos JDBC de la conexi\u00F3n Mondrian es un tipo no v\u00E1lido ({0}).

jsexception.no.connection.selected=No se ha seleccionado ninguna conexi\u00F3n.
jsexception.no.export.folder.specified=No se ha especificado ninguna carpeta de exportaci\u00F3n.
jsexception.no.export.zip.file.specified=No se ha especificado ning\u00FAn archivo ZIP de exportaci\u00F3n.
jsexception.no.import.folder.specified=No se ha especificado ninguna carpeta de importaci\u00F3n.
jsexception.no.import.zip.file.specified=No se ha especificado ning\u00FAn archivo ZIP de importaci\u00F3n.
jsexception.no.input.parameter.specified=No se ha especificado ning\u00FAn par\u00E1metro de entrada.
jsexception.no.olap.client.connection=No se ha encontrado ninguna conexi\u00F3n de cliente OLAP.
jsexception.no.secure.olap.client.connection=No se ha encontrado ninguna conexi\u00F3n de cliente OLAP segura.
jsexception.no.olap.model.created.for=No se ha creado ning\u00FAn modelo OLAP para {0}.
jsexception.no.olap.model.name=No se ha especificado ning\u00FAn modelo OLAP.
jsexception.no.olap.model.retrieved=No se ha podido recuperar ning\u00FAn modelo OLAP.
jsexception.no.output.parameter.specified=No se ha especificado ning\u00FAn par\u00E1metro de salida.
jsexception.no.persistent.class.mapped.to=No se ha asignado ninguna clase persistente a {0}.
jsexception.no.resource.data.provider.found=No se ha encontrado ning\u00FAn proveedor de datos de recursos para el ID {0}.
jsexception.no.such.object.permission=El permiso de objeto especificado no existe.
jsexception.no.such.role=No existe la funci\u00F3n {0}.
jsexception.no.such.user=No existe el usuario {0}.
jsexception.no.uri.or.recipient.given=No se ha especificado ning\u00FAn URI o destinatario.
jsexception.no.values.to.enumerate={0} no es un URI de recursos v\u00E1lido.
jsexception.no.values.to.enumerate={0} no es un URI de recursos v\\u00e1lido.
jsexception.null.uri=URI nulo.

jsexception.output.stream.already.closed=La secuencia de salida ya est\u00E1 cerrada.

jsexception.property.not.a.list=La propiedad {0} del bean {1} no es una propiedad de lista.
jsexception.property.not.a.map=La propiedad {0} del bean {1} no es una propiedad de asignaci\u00F3n.
jsexception.property.not.a.text=La propiedad {0} del bean {1} no es una propiedad de texto.

jsexception.query.datasource.has.an.invalid.type=El origen de datos de la consulta tiene un tipo no v\u00E1lido ({0}).

jsexception.report.job.not.found=No existe un trabajo de informe con el ID {0}.
jsexception.report.resource.already.exists.no.overwrite=El recurso de salida {0} ya existe y el marcador de sobrescritura del trabajo no se ha establecido.
jsexception.report.no.content.resource=El recurso {0} no es un recurso de contenido.
jsexception.report.unit.datasource.has.an.invalid.type=El origen de datos de la unidad de informe tiene un tipo no v\u00E1lido ({0}).
jsexception.report.unknown.output.format=El formato de salida de informe {0} es un formato desconocido.
jsexception.repository.uri.neither.report.nor.folder=El URI de repositorio {0} no es una unidad de informe ni una carpeta.
jsexception.resource.already.exists=El recurso {0} ya existe. Elija un nombre diferente.
jsexception.resource.copyTo.not.implemented=El recurso copyTo no se ha implementado.
jsexception.resource.copyFrom.not.implemented=El recurso copyFrom no se ha implementado.
jsexception.resource.does.not.exist=No existe el recurso {0}.
jsexception.resource.no.match.versions={0}: la versi\u00F3n de cliente {1} no coincide con la versi\u00F3n de repositorio ({2}).
jsexception.resource.of.type.not.found=No se ha encontrado el recurso {0} de tipo {1}.
jsexception.resource.not.report.unit=El recurso {0} no es una unidad de informe.
jsexception.resourcelookup.not.a.resource=ResourceLookup no es un recurso: {0}.
jsexception.folder.delete.root=La carpeta ra\u00EDz no se puede eliminar.
jsexception.report.template.not.found=La URI {0} del repositorio no es una plantilla de informe.
jsexception.report.template.uri.not.specified=La URI de plantilla no se especifica.

jsexception.selected.report.not.adhoc=El informe seleccionado no es un informe ad hoc. No se admiten unidades de informes regulares.
jsexception.session.timeout.occurred=Se ha superado el tiempo de espera de la sesi\u00F3n OLAP.

jsexception.too.many.data.rows=Fallo del exportador debido a demasiadas filas de datos. Puede cambiar los ajustes del exportador para tener una p\u00E1gina por hoja.

jsexception.unable.to.complete.request=El sistema no ha podido completar su solicitud. Puede que su conversaci\u00F3n haya finalizado, caducado o haya sido invalidada.
jsexception.undefined.file.type=No se reconoce este tipo de archivo.
jsexception.unknown.connection.type=No se reconoce este tipo de conexi\u00F3n.
jsexception.unknown.parameter.type.for.multiple.value.input=El tipo de par\u00E1metro {0} no es v\u00E1lido para una entrada de varios valores.
jsexception.unknown.permission.recipient.type=No se reconoce el tipo de destinatario de permiso {0}.
jsexception.unknown.property.filter.operation=No se reconoce la operaci\u00F3n de filtro de propiedades {0}.
jsexception.unknown.timezone=No se reconoce la zona horaria {0}. 
jsexception.uri.not.found=URI {0} no encontrado en el repositorio.
jsexception.user.credentials.are.expired=Las credenciales del usuario {0} han caducado.
jsexception.user.disabled=El usuario {0} est\u00E1 desactivado.
jsexception.user.expired=El usuario {0} ha caducado.
jsexception.user.locked=El usuario {0} est\u00E1 bloqueado.
jsexception.user.not.found=No existe el usuario {0}.

jsexception.move.folder.source.uri.ancestor.destination={0} no se puede mover a {1}. El destino es un elemento secundario del origen.
jsexception.move.folder.to.same.folder=No puede mover la carpeta {0} a la misma carpeta {1}.
jsexception.move.resource.to.same.folder=No puede mover el recurso {0} a la misma carpeta {1}.
jsexception.move.folder.path.already.exists=No puede mover la carpeta {0} a {1}. La carpeta de destino ya contiene un objeto con el mismo nombre.
jsexception.move.resource.path.already.exists=No puede mover el recurso {0} a {1}. El destino ya contiene un objeto con el mismo nombre.
jsexception.copy.resource.referenced.not.readable=Otro recurso hace referencia al recurso {0}, pero no se puede leer.
jsexception.copy.resource.circular.reference=Se ha detectado una referencia circular para el recurso {0}.
jsexception.folder.moved=La carpeta {0} se ha movido a {1}.

report.scheduling.error.filling.report=No se complet\u00F3 el informe. Se produjo un error al ejecutarlo.
report.scheduling.error.exporting.report=No se complet\u00F3 la exportaci\u00F3n a {0}. Un error ha interrumpido el proceso.
report.scheduling.error.saving.to.repository={0} no se ha guardado en el repositorio. Un error ha interrumpido el proceso.
report.scheduling.error.sending.email.notification=No se complet\u00F3 la notificaci\u00F3n de error de trabajo. Se produjo un error al enviarlo.
report.scheduling.error.system=No se complet\u00F3 el trabajo. Se produjo un error del sistema al ejecutarlo.

exception.report.unrecognized.number.type=Tipo num\u00E9rico no reconocido {0}
exception.report.unrecognized.date.type=Tipo de fecha/hora no reconocido {0}
exception.report.unsupported.date.input.value=No puede convertir el valor de entrada {0} del tipo {1} en un par\u00E1metro de fecha/hora.
exception.report.unsupported.date.parameter.type=Tipo de fecha/hora no admitido {0}
exception.report.unsupported.input.control.data.type=No se admite el tipo de datos de control de entrada {0}.

jsexception.view.report.could.not.load=La unidad de informe no existe o no se puede cargar.
jsexception.view.page.does.not.exist=No se ha encontrado la p\u00E1gina {0} en el informe
jsexception.view.report.error=Se ha producido un error durante la generaci\u00F3n del informe
jsexception.export.unknown.argument=No se reconoce la opci\u00F3n {0}.

jsexception.mondrian.no.connection.for.resource=No hay ninguna conexi\u00F3n Mondrian para el recurso {0}.

jsexception.target.org.not.found=No se ha encontrado la organizaci\u00F3n de destino {0} en el repositorio.
jsexception.template.folder.not.found=No se ha encontrado la carpeta de plantilla en el repositorio.

jsexception.search.duplicate.label=Ya existe un objeto con la etiqueta {0} en la carpeta {1}.
jsexception.search.duplicate.name=Ya existe un objeto con el nombre {0} en la carpeta {1}.

report.scheduling.error.saving.data.snapshot.disabled=Guardar datos de instant\u00E1neas est\u00E1 desactivado.
report.scheduling.error.data.snapshot.not.populated=No se han propagado los datos de instant\u00E1nea.
report.scheduling.error.data.snapshot.not.persistable=No se pueden guardar los datos de instant\u00E1nea.
report.scheduling.error.saving.data.snapshot.failed=Error al guardar los datos de la instant\u00E1nea.

exception.remote.resource.already.exists=El recurso {0} ya existe.
exception.remote.resource.not.found=No se ha encontrado el recurso {0}
exception.remote.resource.type.not.supported=El tipo de recurso {0} no es compatible con esta operaci\u00F3n.
exception.remote.folder.not.found=No se encuentra la carpeta {0} o no es una carpeta.
exception.remote.unexpected.error=Error inesperado.
exception.remote.weak.password=Contrase\u00F1a poco segura.
exception.remote.attribute.permission.order.invalid=El permiso de atributo de {0} no se puede modificar a otro permiso m\u00E1s fuerte {1}. Seleccione un permiso m\u00E1s restrictivo o igual que el permiso heredado {2}.
exception.remote.attribute.permission.recipient.invalid=El receptor del permiso de atributo {0} de {1} no es v\u00E1lido.
exception.remote.resource.not.ready=La tarea {0} no ha finalizado a\u00FAn.
exception.remote.no.such.export.process=No hay ninguna tarea de exportaci\u00F3n con el id {0}.
exception.remote.no.such.import.process=No hay ninguna tarea de exportaci\u00F3n con el id {0}.
exception.remote.access.denied=Acceso denegado.
exception.remote.modification.not.allowed=No se permite la modificaci\u00F3n del recurso {0}.
exception.remote.illegal.parameter.value.error=El valor \"{1}\" del par\u00E1metro \"{0}\" no es v\u00E1lido.

exception.remote.query.reference.integrity.error=La consulta tiene referencias rotas o inadecuadas para los campos de consulta.
exception.remote.query.filter.reference.class.error=El filtro hace referencia a un campo {0} con un tipo no admitido {1}
exception.remote.query.order.generic.reference.class.error=La declaraci\u00F3n de orden hace referencia a un campo {0} con un tipo no admitido {1}
exception.remote.query.order.header.null.reference.error=La declaraci\u00F3n de orden de encabezado no tiene ninguna referencia en el nivel de consulta.
exception.remote.query.order.header.reference.class.error=La declaraci\u00F3n de orden de encabezado hace referencia a un campo {0} con un tipo no admitido {1}
exception.remote.query.expansion.header.null.reference.error=La declaraci\u00F3n de expansi\u00F3n de encabezado no tiene ninguna referencia en el nivel de consulta.
exception.remote.query.expansion.level.reference.class.error=La declaraci\u00F3n de expansi\u00F3n de encabezado hace referencia a un campo {0} con un tipo no admitido {1}
exception.remote.query.expansion.level.ambiguous.reference.error=La expansi\u00F3n de encabezado hace referencia a un campo identificable no de forma exclusiva {0}
exception.remote.query.aggregated.field.reference.class.error=La declaraci\u00F3n de expansi\u00F3n de encabezado hace referencia a un campo {0} con un tipo no admitido {1}

exception.remote.mandatory.parameter.error=Falta el par\u00E1metro obligatorio \"{0}\".
exception.remote.mandatory.olap.parameter.select.aggregations.error=Falta el par\u00E1metro obligatorio \"select.aggregations\".
exception.remote.mandatory.olap.parameter.groupBy.columns.error=Falta el par\u00E1metro obligatorio \"groupBy.columns\".
exception.remote.mandatory.olap.parameter.groupBy.aggregations.error=Falta el par\u00E1metro obligatorio \"aggregations\" para \"groupBy.columns\" o \"groupBy.rows\".
exception.remote.parameter.groupBy.multiple.aggregations.error=Se han encontrado varios par\u00E1metros \"aggregations\". Solo se admite un par\u00E1metro para \"groupBy.columns\" o \"groupBy.rows\"
exception.remote.import.failed=Error en la importaci\u00F3n. Raz\u00F3n: {0}
exception.remote.import.failed.zip.error=Error en la importaci\u00F3n. Raz\u00F3n: no se puede leer el archivo comprimido.
exception.remote.import.failed.content.error=Error en la importaci\u00F3n. Motivo: el archivo zip proporcionado no es un archivo de exportaci\u00F3n de JasperReports Server v\u00E1lido.
exception.remote.resource.querying.not.supported=El recurso {0} no admite consultas
exception.remote.version.not.match=Error en la actualizaci\u00F3n: las versiones no coinciden
exception.remote.query.where.parameters.name.is.not.valid=El nombre del par\u00E1metro no es v\u00E1lido. El nombre debe empezar por un car\u00E1cter del alfabeto y solo permitir A-z _ y n\u00FAmeros
exception.remote.serialization.error= Error de serializaci\u00F3n.

exception.remote.query.level.hierarchy.not.valid=Los niveles de una dimensi\u00F3n tienen una jerarqu\u00EDa diferente. Solo se pueden seleccionar los niveles de una sola jerarqu\u00EDa.
exception.remote.olap.query.limit.not.supported=No se admite el l\u00EDmite de la consulta para OLAP.
exception.remote.query.calculated.field.expression.missing=Falta la expresi\u00F3n de campo calculada.
exception.remote.path.list.not.valid=El segmento de ruta contiene caracteres no v\u00E1lidos.
exception.remote.query.calculated.field.expression.not.valid=La expresi\u00F3n de campo calculado de consulta no es v\u00E1lida.
exception.remote.timezone.is.not.valid=La zona horaria {0} no es v\u00E1lida.

#AWS data source specific exception messages
aws.exception.datasource.recovery.base=Se ha producido una excepci\u00F3n durante la recuperaci\u00F3n del origen de datos de AWS: {0}.
aws.exception.datasource.recovery.timeout=Es posible que haya un problema con la URL de JDBC, la configuraci\u00F3n de seguridad de AWS o el proceso de recuperaci\u00F3n del origen de datos de AWS, lo cual puede llevar hasta 2 minutos.
aws.exception.datasource.recovery.instance.not.active=La instancia del origen de datos de AWS no est\u00E1 activa.
aws.exception.datasource.recovery.is.not.possible=El origen de datos de AWS no se puede recuperar autom\u00E1ticamente dado que JasperReports Server y la instancia de la base de datos no se encuentran en el mismo VPC.
aws.exception.datasource.recovery.public.ip.not.provided=Debe especificar la \"IP p\u00FAblica de ingreso\" de este servidor en la configuraci\u00F3n de la nube para utilizar la configuraci\u00F3n y la recuperaci\u00F3n automatizadas del origen de datos de AWS.
aws.exception.datasource.recovery.public.ip.not.determined=No se puede determinar la direcci\u00F3n IP de la instancia para la recuperaci\u00F3n del origen de datos de AWS.
aws.exception.datasource.load.default.credentials=Esta instancia no puede utilizar <b>las credenciales de la instancia de EC2</b> para conectarse autom\u00E1ticamente a Amazon RDS y Amazon Redshift porque no tiene funci\u00F3n de Administraci\u00F3n de identidad y acceso (IAM) asignada. Lea <a class='launcher inline' href='http://community.jaspersoft.com/jaspersoft-aws/launch' target='_blank'>C\u00F3mo lanzar Jaspersoft para AWS</a> para saber c\u00F3mo lanzar un servidor que es capaz de conectarse autom\u00E1ticamente a or\u00EDgenes de datos AWS de forma segura.<br><br>Como soluci\u00F3n alternativa, puede usar <b>las credenciales de AWS</b>.
aws.exception.datasource.rds.vpc.recovery=No se puede asignar autom\u00E1ticamente el grupo de seguridad de VPC denominado {0} a la instancia de RDS {1}. La operaci\u00F3n actualmente no es compatible con la API de AWS. Asigne de forma manual el grupo de seguridad a la instancia de RDS.
aws.exception.datasource.accessKey.invalid=La clave de acceso de AWS no es v\u00E1lida.
aws.exception.datasource.secretKey.invalid=La clave secreta de AWS no es v\u00E1lida.

#AZURE data source specific exception messages
azure.exception.datasource.recovery.public.ip.not.provided=Debe especificar la \"IP p\u00FAblica de ingreso\" de este servidor en la configuraci\u00F3n de la nube para utilizar la configuraci\u00F3n y la recuperaci\u00F3n automatizadas del origen de datos de Azure.
azure.exception.datasource.recovery.firewall.rule.name.not.provided=Debe especificar el \"Nombre de regla de servidor de seguridad\" de este servidor para utilizar la instalaci\u00F3n y la recuperaci\u00F3n automatizadas del origen de datos de Azure.
azure.exception.datasource.recovery.server.name.not.provided=Debe especificar el \"Nombre del servidor\" de este servidor para utilizar la instalaci\u00F3n y la recuperaci\u00F3n automatizadas del origen de datos de Azure.
azure.exception.datasource.recovery.subscription.id.not.provided=Debe especificar el \"ID de suscripci\u00F3n\" para utilizar la configuraci\u00F3n y la recuperaci\u00F3n automatizadas del origen de datos de Azure.
azure.exception.datasource.recovery.key.store.file.not.provided=Debe especificar el \"Archivo de almacenamiento de claves\" para utilizar la configuraci\u00F3n y la recuperaci\u00F3n automatizadas del origen de datos de Azure.
azure.exception.datasource.recovery.key.store.type.not.provided=Debe especificar el \"Tipo de almac\u00E9n de claves\" para utilizar la configuraci\u00F3n y la recuperaci\u00F3n automatizadas del origen de datos de Azure.
azure.exception.datasource.key.error=Error al leer el certificado del repositorio. Compruebe que el archivo de certificado y la contrase\u00F1a sean v\u00E1lidos.
azure.exception.datasource.auth.error=Error de autenticaci\u00F3n. Compruebe que el ID de suscripci\u00F3n y el certificado sean v\u00E1lidos.
azure.exception.datasource.cannot.retrieve.database.list=No se pueden recuperar las bases de datos de sql management.
azure.exception.datasource.cannot.ensure.firewall.rule=No se puede garantizar la regla de servidor de seguridad de Azure.
azure.exception.datasource.cannot.recover.datasource=No se puede recuperar el origen de datos de Azure.

#Cluster specific exception messages
cluster.exception.session.attribute.missing=Se ha producido un error no relacionado en el servidor. Se ha reiniciado la sesi\u00F3n y se ha perdido el trabajo no guardado. Disculpe las molestias.<p><p>Haga clic en el siguiente v\u00EDnculo para volver a la p\u00E1gina de inicio y empezar de nuevo: <a class=\"launcher inline\" href=\"home.html\">Ir a la p\u00E1gina de inicio</a>. Si se produce otro error, p\u00F3ngase en contacto con el administrador.
cluster.exception.session.attribute.missing.popup=Se ha producido un error no relacionado en el servidor. Se ha reiniciado la sesi\u00F3n y se ha perdido el trabajo no guardado. Disculpe las molestias.<p><p>Haga clic en el siguiente bot\u00F3n para volver a la p\u00E1gina de inicio y empezar de nuevo. Si se produce otro error, p\u00F3ngase en contacto con el administrador.

#Profile attributes substitution error and debug level messages
profile.attribute.exception.substitution.base = Se ha producido un error de sustituci\u00F3n de atributo en el campo \"{1}\" del recurso \"{0}\".
profile.attribute.substitution.not.found = El nombre del atributo \"{0}\" no est\u00E1 definido en el \"{1}\".
profile.attribute.substitution.not.found.in.resource = Se ha producido un error de sustituci\u00F3n de atributo en el campo \"{1}\" del recurso \"{0}\". El nombre del atributo \"{2}\" no est\u00E1 definido en el \"{3}\".
profile.attribute.substitution.category.invalid = En el atributo \"{1}\", la categor\u00EDa \"{0}\" no es v\u00E1lida. Debe ser una de \"{2}\".
profile.attribute.substitution.category.invalid.in.resource = Se ha producido un error de sustituci\u00F3n de atributo en el campo \"{1}\" del recurso \"{0}\". En el atributo \"{3}\", la categor\u00EDa \"{2}\" no es v\u00E1lida. Debe ser una de \"{4}\".
profile.attribute.debug.substitution.success = El atributo \"{0}\" sustituido en el recurso \"{1}\". Nuevo valor de campo \"{2}\": \"{3}\".

#Query execution exceptions.
query.execution.not.found=El ID de ejecuci\u00F3n de consulta \"{0}\" no se ha encontrado en el servidor.
query.execution.cancelled=El ID de ejecuci\u00F3n de consulta \"{0}\" se ha cancelado.
query.datasource.invalid=La fuente de datos \"{0}\" ha provocado un error durante la ejecuci\u00F3n de la consulta.
datasource.connection.failed=Error de conexi\u00F3n de la fuente de datos.

#Paging exceptions.
paging.offset.out.of.range = El intervalo especificado de la fila no es v\u00E1lido. El intervalo debe estar comprendido entre \"{0}\" y \"{1}\".
paging.page.size.out.of.range = El tama\u00F1o especificado de la p\u00E1gina no es v\u00E1lido. El tama\u00F1o de la p\u00E1gina debe ser mayor que \"{0}\".
query.limit.out.of.range = El l\u00EDmite especificado de la consulta no es v\u00E1lido. El l\u00EDmite de la consulte debe estar entre \"{0}\" y \"{1}\".
paging.axis.count.out.of.range=El n\u00FAmero de ejes de paginaci\u00F3n no debe ser superior a 1 para consultas multinivel, o 2 para consultas multiejes.

# Ad Hoc REST
query.where.parameter.not.valid=El par\u00E1metro \"{0}\" presenta un valor no v\u00E1lido \"{1}\" para el operador \"{2}\".
query.field.ids.collision=Los ID del campo de consulta \"{0}\" entran en conflicto con un ID existente del campo de consulta o con el nombre del campo de la fuente de datos.
query.field.ids.metadata.field.collision=Los ID del campo de consulta \"{0}\" entran en conflicto con un nombre de campo existente de metadatos.
query.parameter.name.query.field.id.collision=El nombre de par\u00E1metro de consulta \"{0}\" entra en conflicto con un ID de campo de consulta existente.
query.parameter.name.metadata.field.collision=El nombre de par\u00E1metro de consulta \"{0}\" entra en conflicto con el campo de metadatos.
report.missing.data.source.fields=El informe contiene uno o varios elementos que no se encuentran en los datos de origen. Debe editar la vista ad hoc que se ha utilizado para crear este informe y volver a guardar el informe.
adhoc.missing.data.source.fields=La vista contiene uno o varios elementos que no se encuentran en los datos de origen. Debe editar la vista ad hoc.
query.in.memory.datasource.type.not.supported=El valor de \"{0}\" no es v\u00E1lido. La fuente de datos de la memoria interna es del tipo \"{1}\", que no est\u00E1 admitido para la ejecuci\u00F3n de la consulta.
expression.representation.required = En \"{0}\", se debe especificar tanto el objeto de la expresi\u00F3n como una cadena de expresi\u00F3n, pero ambas representaciones son nulas.
query.datasource.not.found=No se ha encontrado el URI de la fuente de datos \"{0}\" en el servidor.
query.datasource.access.denied=No tiene permiso para acceder a la fuente de datos \"{0}\".
query.aggregate.definition.error=La definici\u00F3n agregada no puede tener una funci\u00F3n agregada y una expresi\u00F3n.
query.fields.from.multiple.dataislands=Los campos de consulta \"{0}\" y \"{1}\" est\u00E1n en islas de datos separadas y no pueden consultarse conjuntamente.
query.datasource.type.not.supported=La fuente de datos \"{0}\" es de un tipo no admitido en la ejecuci\u00F3n de la consulta.
query.datasource.olap.view.not.supported=La fuente de datos \"{0}\" se basa en una vista OLAP, lo que no est\u00E1 admitido en la ejecuci\u00F3n de consulta.
query.where.expression.type.not.supported=La expresi\u00F3n WHERE de la consulta del tipo \"{0}\" no est\u00E1 admitida.
query.expression.not.valid=La expresi\u00F3n de la consulta no es v\u00E1lida.
query.aggregate.expression.not.valid=La expresi\u00F3n de agregaci\u00F3n \"{1}\" del campo agregado \"{0}\" no es una expresi\u00F3n v\u00E1lida.
query.aggregation.expression.not.valid=La expresi\u00F3n de agregaci\u00F3n de consulta no es v\u00E1lida

query.select.illegal.fields.state=No se permite la selecci\u00F3n simult\u00E1nea de campos y campos distintos.

query.aggregation.function.name.not.valid=El nombre de la funci\u00F3n de agregaci\u00F3n \"{1}\" del campo agregado \"{0}\" no es una funci\u00F3n reconocida.
query.groupBy.allGroup.not.first=En los grupos de consulta \"{0}\", \"allGroup\" debe estar en la primera posici\u00F3n.
query.groupBy.categorizer.not.valid=El clasificador GROUP BY \"{0}\" no tiene un nombre v\u00E1lido.
query.multiAxis.aggregation.is.empty=La matriz de agregaci\u00F3n en una consulta multieje no puede estar vac\u00EDa.
query.orderBy.topOrBottom.limit.not.valid=El l\u00EDmite ORDER BY \"{0}\" tiene un valor de \"{1}\" pero no puede ser inferior a 1.
query.orderBy.level.reference.not.valid=El nivel ORDER BY de la consulta \"{0}\" no se puede resolver. Falta el indicador de agregaci\u00F3n o el fieldRef no es v\u00E1lido.

query.where.parameters.expression.not.valid=Las expresiones de par\u00E1metros de la cl\u00E1usula WHERE no son compatibles o no son v\u00E1lidas.
query.where.parameters.expression.type.not.valid=El par\u00E1metro \"{0}\" de la expresi\u00F3n WHERE no es v\u00E1lido para el operador \"{1}\". Debe ser de alguno de estos tipos: \"{2}\"
query.details.unsupported=Las consultas multieje no admiten detalles. La expresi\u00F3n SELECT no puede definir ning\u00FAn campo.
query.invalid.structure=La consulta debe contener al menos una cl\u00E1usula no vac\u00EDa, ya sea la expresi\u00F3n SELECT o GROUP BY.
query.transformation.topn.not.allowed.aggregations.in.rows=Los filtros N superior o N inferior no est\u00E1n permitidos cuando una consulta multieje contiene agregaciones en filas.
attribute.patterns.contains.invalid = La lista de patrones de atributos contiene patrones no v\u00E1lidos {0}. Le falta el siguiente grupo de captura de nombres: {1}

query.expression.operands.size.out.of.bound=El tama\u00F1o de los operandos de las expresiones de consulta \"{0}\" debe estar entre \"{1}\" y \"{2}\".
query.expansion.level.reference.not.valid = El nivel de expansi\u00F3n de consulta \"{0}\" no se puede resolver.
query.metadata.fields.not.found = Los campos de consulta \"{0}\" no existen en la fuente de datos.