#
# Copyright (C) 2005 - 2019 TIBCO Software Inc. All rights reserved.
# http://www.jaspersoft.com.
#
# Unless you have purchased a commercial license agreement from Jaspersoft,
# the following license terms apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

jsexception.access.denied=Sie sind nicht berechtigt, die angeforderte Aktion auszuf\u00FChren. Melden Sie sich als berechtigter Benutzer an, sofern Ihnen dies m\u00F6glich ist.
jsexception.any={0}

jsexception.bean.has.no.method=Die Bean mit dem Namen \"{0}\" verf\u00FCgt nicht \u00FCber die Methode \"{1}\".
jsexception.bean.name.not.found.for.interface=F\u00FCr die Schnittstelle \"{0}\" wurde kein Bean-Name gefunden.
jsexception.bean.no.name=Eine Bean mit dem Namen \"{0}\" wurde nicht gefunden.
jsexception.bean.not.a.ReportDataSourceService=Die Bean \"{0}\" ist kein ReportDataSourceService.

jsexception.call.not.supported=Der Aufruf wird von Ressourcen-Lookup-Objekten nicht unterst\u00FCtzt.
jsexception.connection.type.not.suported=Der Verbindungstyp wird nicht unterst\u00FCtzt.
jsexception.connection.uri.not.specified=Der Verbindungs-URI ist nicht angegeben.
jsexception.could.not.find.resource.with.uri=Die Ressource mit dem URI \"{0}\" wurde nicht gefunden. 
jsexception.could.not.find.content.resource.with.uri=Die Inhaltsressource mit dem URI \"{0}\" wurde nicht gefunden.
jsexception.unexpected.resource.type.at.uri=Unerwarteter Typ ({0}) der Ressource mit URI {1}. 

jsexception.default.message=Ein unbekannter Fehler ist aufgetreten. Wenden Sie sich an Ihren Systemadministrator.

jsexception.error.creating.connection=Beim Herstellen der Verbindung ist ein Fehler aufgetreten. Versuchen Sie es erneut.
jsexception.parameter.has.multiple.values=Der Parameter \"{0}\" weist mehrere Werte auf.

jsexception.parameter.has.no.value=Der Parameter \"{0}\" weist keinen Wert auf.


jsexception.failed.to.create.connection=Die Verbindung konnte nicht hergestellt werden.
jsexception.failed.to.save.connection=Die Verbindung wurde nicht gespeichert.
jsexception.failed.to.save.connection.changes=Die \u00C4nderungen an der Verbindung wurden nicht gespeichert.
jsexception.file.resource.is.reference=Die Dateiressource \"{0}\" ist ein Verweis und enth\u00E4lt keine Daten.
jsexception.file.resource.no.match.type=Der deklarierte Typ der Ressource ({0}) entspricht nicht dem tats\u00E4chlichen Typ des Verweises ({1}).
jsexception.folder.already.exists=Es ist bereits ein Ordner mit dem Namen \"{0}\" vorhanden. W\u00E4hlen Sie einen anderen Namen aus.
jsexception.folder.details.not.found=In den Importinformationen wurden keine Ordnerdetails f\u00FCr den Ordner \"{0}\" gefunden. 
jsexception.folder.not.found=Der Ordner \"{0}\" wurde nicht gefunden. 
jsexception.folder.not.found.at=Der Ordner befindet sich nicht in \"{0}\".
jsexception.folder.duplicate.name=Es befindet sich bereits ein Ordner mit dem Namen \"{0}\" in \"{1}\".
jsexception.folder.duplicate.label=Doppelte Ordnerbezeichnung \"{0}\" im Ordner \"{1}\".
jsexception.folder.too.long.uri=Der URI f\u00FCr den Ordner ist zu lang. Die Maximall\u00E4nge betr\u00E4gt {0} Zeichen.
jsexception.folder.creation.not.allowed=\"{0}\" ist ein reservierter Name und in \"{1}\" nicht zul\u00E4ssig.

jsexception.got.null.schema.source.wrapper=Der Subflow hat einen NULL-Wrapper f\u00FCr die Schemaquelle zur\u00FCckgegeben.
jsexception.got.null.access.grant.source.wrapper=Der Subflow hat einen NULL-Wrapper f\u00FCr die Quelle der Zugriffsgew\u00E4hrung zur\u00FCckgegeben.
jsexception.got.null.connection.back=Der Subflow hat eine NULL-Verbindung zur\u00FCckgegeben.

jsexception.implementation.class.does.not.implement=Die Implementierungsklasse \"{0}\" implementiert \"{1}\" nicht.
jsexception.implementation.class.not.found=F\u00FCr \"{0}\" wurde keine Implementierungsklasse gefunden.
jsexception.import.directory.not.found=Das Importverzeichnis \"{0}\" wurde nicht gefunden.
jsexception.import.module.not.found=Das Importmodul \"{0}\" wurde nicht gefunden.
jsexception.import.multiple.values.for.single.parameter=F\u00FCr den Parameter \"{0}\" des Berichts \"{1}\", der nur einen Wert akzeptiert, wurden mehrere Parameterwerte erkannt.
jsexception.input.stream.exhausted=Der Eingabe-Stream wurde vor dem Lesen von {0} Bytes beendet.
jsexception.invalid.bean.datasource=Die Bean-Datenquelle \"{0}\" ist ung\u00FCltig.
jsexception.invalid.class.attribute.for.model.tag=Das Klassenattribut f\u00FCr das Modell-Tag, Ressource \"{0}\", ist ung\u00FCltig.
jsexception.invalid.jdbc.datasource=Die JDBC-Datenquelle \"{0}\" ist ung\u00FCltig.
jsexception.invalid.aws.datasource=Die AWS-Datenquelle \"{0}\" ist ung\u00FCltig.
jsexception.invalid.azureSql.datasource=Die Azure-SQL-Datenquelle \"{0}\" ist ung\u00FCltig.
jsexception.invalid.jndi.jdbc.datasource=Die JNDI/JDBC-Datenquelle \"{0}\" ist ung\u00FCltig.
jsexception.invalid.olap.datasource=Die OLAP-Datenquelle \"{0}\" ist ung\u00FCltig.
jsexception.invalid.resource.reference.source=Die Quelle f\u00FCr den Ressourcenverweis \"{0}\" ist ung\u00FCltig.
jsexception.invalid.session=Die aktuelle Sitzung ist ung\u00FCltig. Vergewissern Sie sich, dass der Server ausgef\u00FChrt wird, und melden Sie sich erneut an.
jsexception.invalid.uri=Der URI \"{0}\" ist ung\u00FCltig.

jsexception.jar.entry.not.found=Es wurde kein JAR-Eintrag f\u00FCr die URL \"{0}\" gefunden.
jsexception.jar.malformed.url=Die JAR-URL \"{0}\" weist eine fehlerhafte Syntax auf.
jsexception.jasperprint.not.found=Das JasperPrint-Objekt \"{0}\" wurde nicht gefunden.

jsexception.job.has.more.than.one.trigger=Der Auftrag \"{0}\" weist mehrere Trigger auf.
jsexception.job.no.versions.match=Die Clientversion {0} ist nicht die aktuelle Version ({1}).
jsexception.job.unknown.calendar.trigger.days.type=Der Kalendertrigger weist den unbekannten Tagestyp \"{0}\" auf.
jsexception.job.unknown.interval.unit=Der Berichtsauftrag weist die unbekannte Intervalleinheit \"{0}\" auf.
jsexception.job.unknown.start.type=Der Berichtsauftrag weist den unbekannten Starttyp \"{0}\" auf.
jsexception.job.unknown.trigger.bean.class=Der Berichtsauftragstrigger weist die unbekannte Bean-Klasse \"{0}\" auf.
jsexception.job.unknown.trigger.type=Der Berichtsauftrag weist den unbekannten Triggertyp \"{0}\" auf.

jsexception.missing.olap.connection=Die OLAP-Verbindung fehlt.
jsexception.missing.olap.connection.reference=Der Verweis auf die OLAP-Verbindung fehlt.
jsexception.mondrian.jdbc.datasource.has.an.invalid.type=Die JDBC-Datenquelle f\u00FCr die Mondrian-Verbindung weist einen ung\u00FCltigen Typ ({0}) auf.

jsexception.no.connection.selected=Es wurde keine Verbindung ausgew\u00E4hlt.
jsexception.no.export.folder.specified=Es wurde kein Ordner f\u00FCr den Export angegeben.
jsexception.no.export.zip.file.specified=Es wurde keine ZIP-Datei f\u00FCr den Export angegeben.
jsexception.no.import.folder.specified=Es wurde kein Ordner f\u00FCr den Import angegeben.
jsexception.no.import.zip.file.specified=Es wurde keine ZIP-Datei f\u00FCr den Import angegeben.
jsexception.no.input.parameter.specified=Es wurde kein Eingabeparameter angegeben.
jsexception.no.olap.client.connection=Es wurde keine OLAP-Clientverbindung gefunden.
jsexception.no.secure.olap.client.connection=Es wurde keine sichere OLAP-Clientverbindung gefunden.
jsexception.no.olap.model.created.for=Es wurde kein OLAP-Modell f\u00FCr \"{0}\" erstellt.
jsexception.no.olap.model.name=Es wurde kein OLAP-Modell angegeben.
jsexception.no.olap.model.retrieved=Es konnte kein OLAP-Modell abgerufen werden.
jsexception.no.output.parameter.specified=Es wurde kein Ausgabeparameter angegeben.
jsexception.no.persistent.class.mapped.to=\"{0}\" ist keine persistente Klasse zugeordnet.
jsexception.no.resource.data.provider.found=Es wurde kein Ressourcen-Datenprovider f\u00FCr ID \"{0}\" gefunden.
jsexception.no.such.object.permission=Die angegebene Objektberechtigung ist nicht vorhanden.
jsexception.no.such.role=Die Rolle \"{0}\" ist nicht vorhanden.
jsexception.no.such.user=Der Benutzer \"{0}\" ist nicht vorhanden.
jsexception.no.uri.or.recipient.given=Es wurde kein URI bzw. Empf\u00E4nger angegeben.
jsexception.no.values.to.enumerate=\"{0}\" ist kein g\u00FCltiger Ressourcen-URI.
jsexception.no.values.to.enumerate=\"{0}\" ist kein g\\u00fcltiger Ressourcen-URI.
jsexception.null.uri=Null-URI.

jsexception.output.stream.already.closed=Der Ausgabe-Stream ist bereits geschlossen.

jsexception.property.not.a.list=Die Eigenschaft \"{0}\" von Bean \"{1}\" ist keine Listeneigenschaft.
jsexception.property.not.a.map=Die Eigenschaft \"{0}\" von Bean \"{1}\" ist keine Zuordnungseigenschaft.
jsexception.property.not.a.text=Die Eigenschaft \"{0}\" von Bean \"{1}\" ist keine Texteigenschaft.

jsexception.query.datasource.has.an.invalid.type=Die Datenquelle f\u00FCr die Abfrage weist einen ung\u00FCltigen Typ ({0}) auf.

jsexception.report.job.not.found=Es wurde kein Berichtsauftrag mit der ID \"{0}\" gefunden.
jsexception.report.resource.already.exists.no.overwrite=Die Ausgaberessource \"{0}\" ist bereits vorhanden, und das Flag zum \u00DCberschreiben von Auftr\u00E4gen ist nicht gesetzt.
jsexception.report.no.content.resource=Die Ressource \"{0}\" ist keine Inhaltsressource.
jsexception.report.unit.datasource.has.an.invalid.type=Die Datenquelle f\u00FCr die Berichtseinheit weist einen ung\u00FCltigen Typ ({0}) auf.
jsexception.report.unknown.output.format=Das Berichtsausgabeformat \"{0}\" ist unbekannt.
jsexception.repository.uri.neither.report.nor.folder=Der Repository-URI \"{0}\" ist weder eine Berichtseinheit noch ein Ordner.
jsexception.resource.already.exists=Die Ressource \"{0}\" ist bereits vorhanden. W\u00E4hlen Sie einen anderen Namen aus.
jsexception.resource.copyTo.not.implemented=copyTo ist f\u00FCr die Ressource nicht implementiert.
jsexception.resource.copyFrom.not.implemented=copyFrom ist f\u00FCr die Ressource nicht implementiert.
jsexception.resource.does.not.exist=Die Ressource \"{0}\" ist nicht vorhanden.
jsexception.resource.no.match.versions={0}: Die Clientversion {1} entspricht nicht der Repository-Version ({2}).
jsexception.resource.of.type.not.found=Die Ressource \"{0}\" vom Typ \"{1}\" wurde nicht gefunden.
jsexception.resource.not.report.unit=Die Ressource \"{0}\" ist keine Berichtseinheit.
jsexception.resourcelookup.not.a.resource=ResourceLookup ist keine Ressource: {0}.
jsexception.folder.delete.root=Der Stammordner kann nicht gel\u00F6scht werden.
jsexception.report.template.not.found=Der Repository-URI \"{0}\" ist keine Berichtsvorlage.
jsexception.report.template.uri.not.specified=Der Vorlagen-URI ist nicht angegeben.

jsexception.selected.report.not.adhoc=Der ausgew\u00E4hlte Bericht ist kein Ad-hoc-Bericht. Regul\u00E4re Berichtseinheiten werden nicht unterst\u00FCtzt.
jsexception.session.timeout.occurred=Bei der OLAP-Sitzung ist ein Timeout aufgetreten.

jsexception.too.many.data.rows=Der Excel-Export ist fehlgeschlagen, weil zu viele Datenzeilen vorliegen. Sie k\u00F6nnen die Exporteinstellungen auf eine Seite pro Arbeitsblatt festlegen.

jsexception.unable.to.complete.request=Das System konnte die Anforderung nicht abschlie\u00DFen. Ihre Unterhaltung ist m\u00F6glicherweise beendet, abgelaufen oder f\u00FCr ung\u00FCltig erkl\u00E4rt worden.
jsexception.undefined.file.type=Der Dateityp wird nicht erkannt.
jsexception.unknown.connection.type=Der Verbindungstyp wird nicht erkannt.
jsexception.unknown.parameter.type.for.multiple.value.input=Der Parametertyp \"{0}\" l\u00E4sst die Eingabe mehrerer Werte nicht zu.
jsexception.unknown.permission.recipient.type=Der Typ \"{0}\" des Berechtigungsempf\u00E4ngers wird nicht erkannt.
jsexception.unknown.property.filter.operation=Der Eigenschaftenfilter-Vorgang \"{0}\" wird nicht erkannt.
jsexception.unknown.timezone=Die Zeitzone \"{0}\" wird nicht erkannt. 
jsexception.uri.not.found=Der URI \"{0}\" wurde im Repository nicht gefunden.
jsexception.user.credentials.are.expired=Die Anmeldeinformationen von Benutzer \"{0}\" sind abgelaufen.
jsexception.user.disabled=Der Benutzer \"{0}\" ist deaktiviert.
jsexception.user.expired=Der Benutzer \"{0}\" ist abgelaufen.
jsexception.user.locked=Der Benutzer \"{0}\" ist gesperrt.
jsexception.user.not.found=Der Benutzer \"{0}\" wurde nicht gefunden.

jsexception.move.folder.source.uri.ancestor.destination=\"{0}\" kann nicht nach \"{1}\" verschoben werden. Das Ziel ist ein untergeordnetes Element der Quelle.
jsexception.move.folder.to.same.folder=Der Ordner \"{0}\" kann nicht in denselben Ordner \"{1}\" verschoben werden.
jsexception.move.resource.to.same.folder=Die Ressource \"{0}\" kann nicht in denselben Ordner \"{1}\" verschoben werden.
jsexception.move.folder.path.already.exists=Der Ordner \"{0}\" kann nicht nach \"{1}\" verschoben werden. Der Zielordner enth\u00E4lt bereits ein Objekt mit demselben Namen.
jsexception.move.resource.path.already.exists=Die Ressource \"{0}\" kann nicht nach \"{1}\" verschoben werden. Das Ziel enth\u00E4lt bereits ein Objekt mit demselben Namen.
jsexception.copy.resource.referenced.not.readable=Auf die Ressource \"{0}\" wird von einer anderen Ressource verwiesen, sie kann jedoch nicht gelesen werden.
jsexception.copy.resource.circular.reference=Es wurde ein zirkul\u00E4rer Verweis f\u00FCr die Ressource \"{0}\" erkannt.
jsexception.folder.moved=Der Ordner \"{0}\" wurde nach \"{1}\" verschoben.

report.scheduling.error.filling.report=Der Bericht wurde nicht abgeschlossen. Bei der Ausf\u00FChrung ist ein Fehler aufgetreten.
report.scheduling.error.exporting.report=Der Export nach \"{0}\" wurde nicht abgeschlossen. Der Vorgang wurde durch einen Fehler unterbrochen.
report.scheduling.error.saving.to.repository=\"{0}\" wurde nicht im Repository gespeichert. Der Vorgang wurde durch einen Fehler unterbrochen.
report.scheduling.error.sending.email.notification=Die Benachrichtigung zum Auftragsfehler wurde nicht abgeschlossen. Beim Senden ist ein Fehler aufgetreten.
report.scheduling.error.system=Der Auftrag wurde nicht abgeschlossen. Bei der Ausf\u00FChrung ist ein Systemfehler aufgetreten.

exception.report.unrecognized.number.type=Nicht erkannter numerischer Typ \"{0}\"
exception.report.unrecognized.date.type=Nicht erkannter Datums-/Uhrzeittyp \"{0}\"
exception.report.unsupported.date.input.value=Der Eingabewert \"{0}\" vom Typ \"{1}\" kann nicht in einen Datums-/Uhrzeit-Parameter konvertiert werden.
exception.report.unsupported.date.parameter.type=Nicht unterst\u00FCtzter Datums-/Uhrzeittyp \"{0}\"
exception.report.unsupported.input.control.data.type=Der Datentyp \"{0}\" f\u00FCr das Eingabesteuerelement wird nicht unterst\u00FCtzt.

jsexception.view.report.could.not.load=Die Berichtseinheit wurde nicht gefunden, oder sie kann nicht geladen werden.
jsexception.view.page.does.not.exist=Seite {0} wurde im Bericht nicht gefunden.
jsexception.view.report.error=Beim Generieren des Berichts ist ein Fehler aufgetreten.
jsexception.export.unknown.argument=Die Option \"{0}\" wird nicht erkannt.

jsexception.mondrian.no.connection.for.resource=F\u00FCr die Ressource \"{0}\" ist keine Mondrian-Verbindung vorhanden.

jsexception.target.org.not.found=Die Zielorganisation \"{0}\" wurde im Repository nicht gefunden.
jsexception.template.folder.not.found=Der Vorlagenordner wurde im Repository nicht gefunden.

jsexception.search.duplicate.label=Ein Objekt mit der Bezeichnung \"{0}\" ist im Ordner \"{1}\" bereits vorhanden.
jsexception.search.duplicate.name=Ein Objekt mit dem Namen \"{0}\" ist im Ordner \"{1}\" bereits vorhanden.

report.scheduling.error.saving.data.snapshot.disabled=Das Speichern von Datenschnappsch\u00FCssen wurde deaktiviert.
report.scheduling.error.data.snapshot.not.populated=Der Datenschnappschuss enthielt keine Daten.
report.scheduling.error.data.snapshot.not.persistable=Der Datenschnappschuss kann nicht gespeichert werden.
report.scheduling.error.saving.data.snapshot.failed=Fehler beim Speichern des Datenschnappschusses.

exception.remote.resource.already.exists=Die Ressource \"{0}\" ist bereits vorhanden.
exception.remote.resource.not.found=Die Ressource \"{0}\" wurde nicht gefunden.
exception.remote.resource.type.not.supported=Der Ressourcentyp \"{0}\" wird von diesem Vorgang nicht unterst\u00FCtzt.
exception.remote.folder.not.found=Der Ordner \"{0}\" wurde nicht gefunden, oder es handelt sich nicht um einen Ordner.
exception.remote.unexpected.error=Unerwarteter Fehler.
exception.remote.weak.password=Schwaches Passwort.
exception.remote.attribute.permission.order.invalid=Die Attributberechtigung f\u00FCr {0} kann nicht in die umfassendere Berechtigung {1} ge\u00E4ndert werden. W\u00E4hlen Sie eine Berechtigung aus, die restriktiver oder gleichwertig mit der vererbten Berechtigung {2} ist.
exception.remote.attribute.permission.recipient.invalid=Der Attributberechtigungsempf\u00E4nger {0} f\u00FCr {1} ist ung\u00FCltig.
exception.remote.resource.not.ready=Die Aufgabe \"{0}\" ist noch nicht beendet.
exception.remote.no.such.export.process=Es gibt keine Exportaufgabe mit der ID {0}.
exception.remote.no.such.import.process=Es gibt keine Importaufgabe mit der ID {0}.
exception.remote.access.denied=Zugriff verweigert.
exception.remote.modification.not.allowed=Die Ressource \"{0}\" darf nicht ge\u00E4ndert werden.
exception.remote.illegal.parameter.value.error=Der Wert \"{1}\" des Parameters \"{0}\" ist ung\u00FCltig.

exception.remote.query.reference.integrity.error=Die Abfrage enth\u00E4lt besch\u00E4digte oder nicht angemessene Verweise auf Abfragefelder.
exception.remote.query.filter.reference.class.error=Filter verweist auf Feld {0} mit nicht unterst\u00FCtztem Typ {1}.
exception.remote.query.order.generic.reference.class.error=Bestell\u00FCbersicht verweist auf Feld {0} mit nicht unterst\u00FCtztem Typ {1}.
exception.remote.query.order.header.null.reference.error=Kopfzeile in Bestell\u00FCbersicht enth\u00E4lt keinen Verweis auf Abfrageebene.
exception.remote.query.order.header.reference.class.error=Kopfzeile in Bestellschein verweist auf Feld {0} mit nicht unterst\u00FCtztem Typ {1}.
exception.remote.query.expansion.header.null.reference.error=Kopfzeile in Erweiterungs\u00FCbersicht enth\u00E4lt keinen Verweis auf Abfrageebene.
exception.remote.query.expansion.level.reference.class.error=Kopfzeile in Erweiterungs\u00FCbersicht verweist auf Feld {0} mit nicht unterst\u00FCtztem Typ {1}.
exception.remote.query.expansion.level.ambiguous.reference.error=Kopfzeile in Erweiterung verweist auf nicht eindeutig identifizierbares Feld {0}.
exception.remote.query.aggregated.field.reference.class.error=Kopfzeile in Erweiterungs\u00FCbersicht verweist auf Feld {0} mit nicht unterst\u00FCtztem Typ {1}.

exception.remote.mandatory.parameter.error=Der obligatorische Parameter \"{0}\" fehlt.
exception.remote.mandatory.olap.parameter.select.aggregations.error=Der obligatorische Parameter \"select.aggregations\" fehlt.
exception.remote.mandatory.olap.parameter.groupBy.columns.error=Der obligatorische Parameter \"groupBy.columns\" fehlt.
exception.remote.mandatory.olap.parameter.groupBy.aggregations.error=Der obligatorische Parameter \"aggregations\" f\u00FCr \"groupBy.columns\" oder \"groupBy.rows\" fehlt.
exception.remote.parameter.groupBy.multiple.aggregations.error=Es wurden mehrere \"aggregations\"-Parameter gefunden. F\u00FCr \"groupBy.columns\" oder \"groupBy.rows\" ist nur ein Parameter zul\u00E4ssig.
exception.remote.import.failed=Der Import ist fehlgeschlagen. Grund: {0}
exception.remote.import.failed.zip.error=Der Import ist fehlgeschlagen. Grund: Die ZIP-Datei kann nicht gelesen werden.
exception.remote.import.failed.content.error=Der Import ist fehlgeschlagen. Grund: Die angegebene ZIP-Datei ist keine g\u00FCltige Exportdatei von JasperReports Server.
exception.remote.resource.querying.not.supported=Die Ressource \"{0}\" unterst\u00FCtzt keine Abfragen.
exception.remote.version.not.match=Die Aktualisierung ist fehlgeschlagen. Die Versionen stimmen nicht \u00FCberein.
exception.remote.query.where.parameters.name.is.not.valid=Der Parametername ist ung\u00FCltig. Der Name muss mit einem Buchstaben beginnen und darf nur die Zeichen A-z _ und Zahlen enthalten.
exception.remote.serialization.error= Serialisierungsfehler.

exception.remote.query.level.hierarchy.not.valid=Die Ebenen einer Dimension besitzen eine unterschiedliche Hierarchie. Es k\u00F6nnen nur Ebenen aus einer einzigen Hierarchie ausgew\u00E4hlt werden.
exception.remote.olap.query.limit.not.supported=Abfragelimit wird f\u00FCr OLAP nicht unterst\u00FCtzt.
exception.remote.query.calculated.field.expression.missing=Ausdruck f\u00FCr berechnetes Feld fehlt.
exception.remote.path.list.not.valid=Das Pfadsegment enth\u00E4lt ung\u00FCltige Zeichen.
exception.remote.query.calculated.field.expression.not.valid=Ausdruck f\u00FCr berechnetes Feld in Abfrage ist ung\u00FCltig.
exception.remote.timezone.is.not.valid=Die Zeitzone {0} ist ung\u00FCltig.

#AWS data source specific exception messages
aws.exception.datasource.recovery.base=Bei der Wiederherstellung der AWS-Datenquelle ist eine Ausnahme aufgetreten: {0}.
aws.exception.datasource.recovery.timeout=M\u00F6glicherweise gibt es ein Problem mit der JDBC-URL, den AWS-Sicherheitseinstellungen oder dem Wiederherstellungsvorgang f\u00FCr die AWS-Datenquelle, der bis zu 2 Minuten dauern kann.
aws.exception.datasource.recovery.instance.not.active=Die AWS-Datenquelleninstanz ist nicht aktiv.
aws.exception.datasource.recovery.is.not.possible=Die AWS-Datenquelle kann nicht automatisch wiederhergestellt werden, da Ihr JasperReports Server und die Datenbankinstanz sich nicht in derselben VPC befinden.
aws.exception.datasource.recovery.public.ip.not.provided=Sie m\u00FCssen die '\u00D6ffentliche IP f\u00FCr den Zugriff' dieses Servers in den Cloud-Einstellungen angeben, um das automatische Einrichten und Wiederherstellen der AWS-Datenquelle zu erm\u00F6glichen.
aws.exception.datasource.recovery.public.ip.not.determined=Die IP-Adresse der Instanz f\u00FCr die Wiederherstellung der AWS-Datenquelle kann nicht ermittelt werden.
aws.exception.datasource.load.default.credentials=Diese Instanz kann keine <b>EC2-Instanz-Anmeldedaten</b> verwenden, um automatisch eine Verbindung mit Amazon RDS und Amazon Redshift herzustellen, da ihr keine IAM-Rolle (Identity and Access Management, Identit\u00E4ts- und Zugriffsverwaltung) zugewiesen wurde. Bitte lesen Sie <a class='launcher inline' href='http://community.jaspersoft.com/jaspersoft-aws/launch' target='_blank'>Launching Jaspersoft for AWS</a>, um zu erfahren, wie Sie einen Server starten, der automatisch sichere Verbindungen mit AWS-Datenquellen herstellen kann.<br><br>Um dieses Problem zu umgehen, k\u00F6nnen Sie <b>AWS-Anmeldedaten</b> verwenden.
aws.exception.datasource.rds.vpc.recovery=Die VPC-Sicherheitsgruppe \"{0}\" kann nicht automatisch der RDS-Instanz \"{1}\" zugewiesen werden. Der Vorgang wird derzeit nicht von der AWS-API unterst\u00FCtzt. Weisen Sie die Sicherheitsgruppe manuell Ihrer RDS-Instanz zu.
aws.exception.datasource.accessKey.invalid=Der AWS-Zugriffsschl\u00FCssel ist ung\u00FCltig.
aws.exception.datasource.secretKey.invalid=Der AWS-Geheimschl\u00FCssel ist ung\u00FCltig.

#AZURE data source specific exception messages
azure.exception.datasource.recovery.public.ip.not.provided=Sie m\u00FCssen die '\u00D6ffentliche IP f\u00FCr den Zugriff' dieses Servers in den Cloud-Einstellungen angeben, um das automatische Einrichten und Wiederherstellen der Azure-Datenquelle zu erm\u00F6glichen.
azure.exception.datasource.recovery.firewall.rule.name.not.provided=Sie m\u00FCssen den 'Namen der Firewall-Regel' dieses Servers in den Cloud-Einstellungen angeben, um das automatische Einrichten und Wiederherstellen der Azure-Datenquelle zu erm\u00F6glichen.
azure.exception.datasource.recovery.server.name.not.provided=Sie m\u00FCssen den 'Servernamen' dieses Servers angeben, um das automatische Einrichten und Wiederherstellen der Azure-Datenquelle zu erm\u00F6glichen.
azure.exception.datasource.recovery.subscription.id.not.provided=Sie m\u00FCssen die 'Abonnement-ID' angeben, um das automatische Einrichten und Wiederherstellen der Azure-Datenquelle zu erm\u00F6glichen.
azure.exception.datasource.recovery.key.store.file.not.provided=Sie m\u00FCssen die 'Schl\u00FCsselspeicherdatei' angeben, um das automatische Einrichten und Wiederherstellen der Azure-Datenquelle zu erm\u00F6glichen.
azure.exception.datasource.recovery.key.store.type.not.provided=Sie m\u00FCssen den 'Schl\u00FCsselspeichertyp' angeben, um das automatische Einrichten und Wiederherstellen der Azure-Datenquelle zu erm\u00F6glichen.
azure.exception.datasource.key.error=Beim Auslesen der Zertifikatsdatei aus dem Repository\u00A0ist ein Fehler aufgetreten. Vergewissern Sie sich, dass die Zertifikatsdatei und das Passwort g\u00FCltig sind.
azure.exception.datasource.auth.error=Authentifizierungsfehler. Vergewissern Sie sich, dass die Abonnement-ID und das Zertifikat g\u00FCltig sind.
azure.exception.datasource.cannot.retrieve.database.list=Die Datenbanken k\u00F6nnen nicht aus der SQL-Verwaltung abgerufen werden.
azure.exception.datasource.cannot.ensure.firewall.rule=Die Azure-Firewall-Regel kann nicht durchgesetzt werden.
azure.exception.datasource.cannot.recover.datasource=Die Azure-Datenquelle kann nicht wiederhergestellt werden.

#Cluster specific exception messages
cluster.exception.session.attribute.missing=Auf dem Server ist ein unverwandter Fehler aufgetreten. Ihre Sitzung wurde erneut gestartet. Nicht gespeicherte Arbeit ist jedoch verloren gegangen. Entschuldigen Sie die Unannehmlichkeiten.<p><p>Klicken Sie auf den folgenden Link, um zur Startseite zur\u00FCckzukehren und erneut zu beginnen: <a class=\"launcher inline\" href=\"home.html\">Startseite aufrufen</a>. Falls ein weiterer Fehler auftritt, wenden Sie sich an Ihren Administrator.
cluster.exception.session.attribute.missing.popup=Auf dem Server ist ein unverwandter Fehler aufgetreten. Ihre Sitzung wurde erneut gestartet. Nicht gespeicherte Arbeit ist jedoch verloren gegangen. Entschuldigen Sie die Unannehmlichkeiten.<p><p>Klicken Sie unten auf die Schaltfl\u00E4che, um zur Startseite zur\u00FCckzukehren und erneut zu beginnen. Falls ein weiterer Fehler auftritt, wenden Sie sich an Ihren Administrator.

#Profile attributes substitution error and debug level messages
profile.attribute.exception.substitution.base = Im Feld \"{1}\" der Ressource \"{0}\" ist ein Attributersetzungsfehler aufgetreten.
profile.attribute.substitution.not.found = Der Attributname \"{0}\" ist nicht definiert in \"{1}\".
profile.attribute.substitution.not.found.in.resource = Im Feld \"{1}\" von Ressource \"{0}\" ist ein Fehler aufgetreten. Der Attributname \"{2}\" ist nicht in \"{3}\" definiert.
profile.attribute.substitution.category.invalid = In Attribut \"{1}\" ist Kategorie \"{0}\" nicht g\u00FCltig. Es muss eine von \"{2}\" sein.
profile.attribute.substitution.category.invalid.in.resource = Im Feld \"{1}\" von Ressource \"{0}\" ist ein Attributersetzungsfehler aufgetreten. In Attribut  \"{3}\" ist Kategorie \"{2}\" nicht g\u00FCltig. Es muss eine von \"{4}\" sein.
profile.attribute.debug.substitution.success = Das Attribut \"{0}\" wurde in Ressource \"{1}\" ersetzt. Neuer \"{2}\"-Feldwert: \"{3}\".

#Query execution exceptions.
query.execution.not.found=Die Abfrageausf\u00FChrungs-ID \"{0}\" wurde am Server nicht gefunden.
query.execution.cancelled=Die Abfrageausf\u00FChrungs-ID \"{0}\" wurde gel\u00F6scht.
query.datasource.invalid=Die Datenquelle \"{0}\" hat bei der Abfrageausf\u00FChrung einen Fehler verursacht.
datasource.connection.failed=Die Datenquellenverbindung ist fehlgeschlagen.

#Paging exceptions.
paging.offset.out.of.range = Der angegebene Zeilenversatz ist ung\u00FCltig. Der Versatz muss zwischen \"{0}\" und \"{1}\" liegen.
paging.page.size.out.of.range = Die angegebene Seitengr\u00F6\u00DFe ist ung\u00FCltig. Die Seite muss gr\u00F6\u00DFer als \"{0}\" sein.
query.limit.out.of.range = Die angegebene Abfragegrenze ist ung\u00FCltig. Die Abfragegrenze muss zwischen \"{0}\" und \"{1}\" liegen.
paging.axis.count.out.of.range=Die Anzahl der Paginierungsachsen darf nicht gr\u00F6\u00DFer als 1 bei Abfragen mit mehreren Stufen bzw. 2 bei Abfragen mit mehreren Achsen sein.

# Ad Hoc REST
query.where.parameter.not.valid=Der Parameter \"{0}\" enth\u00E4lt den ung\u00FCltigen Wert \"{1}\" f\u00FCr den Operator \"{2}\".
query.field.ids.collision=Die Abfragefeld-IDs \"{0}\" verursachen einen Konflikt mit einer bestehenden Abfragefeld-ID oder einem Feldnamen der Datenquelle.
query.field.ids.metadata.field.collision=Die Abfragefeld-IDs \"{0}\" verursachen einen Konflikt mit einem bestehenden Metadatenfeldnamen.
query.parameter.name.query.field.id.collision=Abfrageparametername \"{0}\" steht mit vorhandener Abfragefeld-ID in Konflikt.
query.parameter.name.metadata.field.collision=Abfrageparametername \"{0}\" steht mit dem Metadaten-Feld in Konflikt.
report.missing.data.source.fields=Der Bericht enth\u00E4lt mindestens ein Element, das sich nicht in den Quelldaten befindet. Bearbeiten Sie die Ad-hoc-Ansicht, aus der dieser Bericht erstellt wurde, und speichern Sie den Bericht erneut.
adhoc.missing.data.source.fields=Die Ansicht enth\u00E4lt mindestens ein Element, das sich nicht in den Quelldaten befindet. Bearbeiten Sie die Ad-hoc-Ansicht.
query.in.memory.datasource.type.not.supported=Der Wert f\u00FCr \"{0}\" ist nicht g\u00FCltig. Die speicherinterne Datenquelle weist den \"{1}\" auf. Dieser wird nicht f\u00FCr die Abfrageausf\u00FChrung unterst\u00FCtzt.
expression.representation.required = In \"{0}\" muss entweder das Ausdrucksobjekt oder eine Ausdruckszeichenfolge angegeben werden, doch beide Darstellungen sind Null.
query.datasource.not.found=Die Datenquellen-URI \"{0}\" wurde am Server nicht gefunden.
query.datasource.access.denied=Sie sind nicht f\u00FCr den Zugriff auf Datenquelle \"{0}\" berechtigt.
query.aggregate.definition.error=Die Aggregatdefinition darf nicht eine Aggregatfunktion und einen Ausdruck gleichzeitig enthalten.
query.fields.from.multiple.dataislands=Die Abfragefelder \"{0}\" und \"{1}\" befinden sich in verschiedenen Dateninseln und k\u00F6nnen nicht gemeinsam abgefragt werden.
query.datasource.type.not.supported=Der Typ von \"{0}\" wird nicht f\u00FCr die Abfrageausf\u00FChrung unterst\u00FCtzt.
query.datasource.olap.view.not.supported=Die Datenquelle \"{0}\" basiert auf einer OLAP-Ansicht, die nicht f\u00FCr die Abfrageausf\u00FChrung unterst\u00FCtzt wird.
query.where.expression.type.not.supported=Der Abfrageausdruck WHERE vom Typ \"{0}\" wird nicht unterst\u00FCtzt.
query.expression.not.valid=Der Abfrageausdruck ist nicht g\u00FCltig.
query.aggregate.expression.not.valid=Der Aggregationsausdruck \"{1}\" im aggregierten Feld \"{0}\" ist kein g\u00FCltiger Ausdruck.
query.aggregation.expression.not.valid=Abfrageaggregationsausdruck ist nicht g\u00FCltig

query.select.illegal.fields.state=Die gleichzeitige Auswahl von Feldern und verschiedenen Feldern ist nicht zul\u00E4ssig

query.aggregation.function.name.not.valid=Der Aggregationsfunktionsname \"{1}\" im aggregierten Feld \"{0}\" ist keine anerkannte Funktion.
query.groupBy.allGroup.not.first=In den Abfragegruppen \"{0}\" muss \"allGroup\" an erster Stelle stehen.
query.groupBy.categorizer.not.valid=Die GROUP BY-Kategorisierung \"{0}\" weist keinen g\u00FCltigen Namen auf.
query.multiAxis.aggregation.is.empty=Die Aggregationsanordnung in einer Mehrfachachsenabfrage darf nicht leer sein.
query.orderBy.topOrBottom.limit.not.valid=Die ORDER BY-Grenze \"{0}\" weist Wert \"{1}\" auf, darf jedoch nicht unter 1 liegen.
query.orderBy.level.reference.not.valid=Die ORDER BY-Abfragestufe \"{0}\" kann nicht aufgel\u00F6st werden. Die Aggregationsflagge fehlt oder der fieldRef ist nicht g\u00FCltig.

query.where.parameters.expression.not.valid=Die Parameterausdr\u00FCcke in der WHERE-Klausel werden nicht unterst\u00FCtzt oder sind ung\u00FCltig.
query.where.parameters.expression.type.not.valid=Der Parameter \"{0}\" des WHERE-Ausdrucks ist f\u00FCr den \"{1}\"-Operator ung\u00FCltig. Er muss einen der folgenden Typen aufweisen: \"{2}\"
query.details.unsupported=Mehrfachachsenabfragen unterst\u00FCtzen keine Details. Der SELECT-Ausdruck kann keine Felder definieren.
query.invalid.structure=Die Abfrage muss mindestens eine nicht leere Klausel enthalten, und zwar entweder den SELECT- oder den GROUP BY-Ausdruck.
query.transformation.topn.not.allowed.aggregations.in.rows=N-Filter oben oder unten sind nicht zul\u00E4ssig, wenn eine Mehrfachachsenabfrage Aggregationen in Zeilen enth\u00E4lt.
attribute.patterns.contains.invalid = Die Liste der Attributmuster enth\u00E4lt das ung\u00FCltige Muster {0}. Es fehlen die n\u00E4chsten Gruppen zur benannten Erfassung: {1}

query.expression.operands.size.out.of.bound=Die Gr\u00F6\u00DFe der Abfrageausdrucksoperanden \"{0}\" muss zwischen \"{1}\" und \"{2}\" liegen.
query.expansion.level.reference.not.valid = Die Abfrageerweiterungsstufe \"{0}\" kann nicht aufgel\u00F6st werden.
query.metadata.fields.not.found = Die Abfragefelder \"{0}\" sind in der Datenquelle nicht vorhanden.